### ISSUE TITLE
scan credential issue

### ISSUE THREAD

**Issue by ctr49** [Secure-Compliance-Solutions-LLC/GVM-Docker#10]
It looks like there is a problem with creating ssh keys for credentialed scans.
When creating a ssh key using "Configuration -> Credentials -> New -> Auto-generate" there is an error message "Internal error".

This is caused by the lack of "ssh-keygen" inside the container.

Installing openssh-client package resolves this issue.

(The other originally reported issue could not be reproduced anymore)

**Comment by pixelsquared** [comment]
The package `ssh-keygen` has been added. Could you verify that this issue is fixed in the latest container?

**Comment by ctr49** [comment]
Yes I can confirm that d2184819729b165b8bd03dc86b5a77133522beea solves the issue. Thanks a lot!
