### ISSUE TITLE
Quits when rsync fails to contact feed.community.greenbone.net

### ISSUE THREAD

**Issue by larsnaesbye** [Secure-Compliance-Solutions-LLC/GVM-Docker#100]
**Describe the bug**
Container exits due to rsyncs failing.

**To Reproduce**
run `docker run --detach --publish 445:9392 --env PASSWORD="admin" --volume gvm-data:/data --name gvm securecompliance/gvm:master`

Observe that container fails after approx. 11 seconds. logs say:
```
Updating NVTs...
rsync: failed to connect to feed.community.greenbone.net (45.135.106.142): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
Updating GVMd data...
rsync: failed to connect to feed.community.greenbone.net (45.135.106.142): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
Updating SCAP data...
rsync: failed to connect to feed.community.greenbone.net (45.135.106.142): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
Updating CERT data...
rsync: failed to connect to feed.community.greenbone.net (45.135.106.142): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
```

**Expected behavior**
That the docker container would start up with synced NVTs etc.

**Additional context**
RedHat 7.6, Docker version 19.03.13.

**Comment by disarmm** [comment]
were you by any chance trying to start multiple scanners at the same time? Are you still having this issue?

**Comment by larsnaesbye** [comment]
No, I wasn't running multiple scanners. I'm thinking it might be a port thing  - does it sync using a port that's not 80 or 443?

**Comment by disarmm** [comment]
yes. it uses rsync on port 873

**Comment by larsnaesbye** [comment]
That's probably it, then.
