### ISSUE TITLE
Consider Alive not working

### ISSUE THREAD

**Issue by jdmcmnm** [Secure-Compliance-Solutions-LLC/GVM-Docker#102]
When scanning hosts that do not allow ping the scan finishes quickly and with no results.  Is anyone else seeing this behavior?  Using the Consider Alive option in the Alive Test option in the target configuration.

**Comment by pixelsquared** [comment]
In the gitter chat @AshleyRoll found that there is a fix https://github.com/greenbone/ospd-openvas/pull/334 but it has not been released.

As a workaround you can create a new Scan Config and edit the `Ping Host: Mark unrechable Hosts as dead (not scanning)` option to be no.
