### ISSUE TITLE
Could not connect to Scanner at /var/run/ospd/ospd.sock

### ISSUE THREAD

**Issue by hanxu98** [Secure-Compliance-Solutions-LLC/GVM-Docker#104]
Could not connect to Scanner at /var/run/ospd/ospd.sock
md manage:WARNING:2020-10-29 09h49.43 UTC:2998: OSP start_scan cc5eaec7-8f55-4858-9199-9f520276a856: Could not connect to Scanner
event task:MESSAGE:2020-10-29 09h49.43 UTC:2998: Status of task 118 (67c97e4a-20a4-48ea-a1a2-d89fe35bc9b8) has changed to Done

**Comment by jakelamotta** [comment]
Not sure why this was closed, we are having the same issue, the permissions of /var/run/ospd/ospd.sock is actively set to 666 in the start.sh script but something is changing them again and therefore GVM can't connect to the scanner. I haven't found out what exactly causes it but it seems to be happening intermittently after restart.
