### ISSUE TITLE
Gvm TLSConnection handshake EOF Error

### ISSUE THREAD

**Issue by dicksnel** [Secure-Compliance-Solutions-LLC/GVM-Docker#105]
**Describe the bug**
I run the Docker image:
`docker run -p 9392:9392 -p 9390:9390 --env PASSWORD="admin" --volume /opt/gvm-data:/data securecompliance/gvm:latest`

I run a simple Python script using the python-gvm library:
`python -m pip install python-gvm`
```
from gvm.connections import TLSConnection
from gvm.protocols.latest import Gmp
from gvm.xml import pretty_print

connection = TLSConnection(hostname='127.0.0.1', port=9390)

with Gmp(connection) as gmp:
    version = gmp.get_version()
    pretty_print(version)
```

Results in the error:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    with Gmp(connection) as gmp:
  File "/usr/local/lib/python3.8/dist-packages/gvm/protocols/base.py", line 51, in __enter__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/gvm/protocols/base.py", line 107, in connect
    self._connection.connect()
  File "/usr/local/lib/python3.8/dist-packages/gvm/connections.py", line 329, in connect
    self._socket.connect((self.hostname, int(self.port)))
  File "/usr/lib/python3.8/ssl.py", line 1342, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.8/ssl.py", line 1333, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1124)
```

Running Python 3.8.6

When I get a bash inside the GVM Docker container and run the exact same script from within the container, it works.

**To Reproduce**
1. Run the Docker image as described above.
2. Run the Python script above.

I tried different Python versions, checked the handshake with openssl, nothing works.

**Expected behavior**
Expected to get a connection with GVM.

**Comment by disarmm** [comment]
I see the problem. We'll push an update in the next 24 hours to fix it.

**Comment by disarmm** [comment]
its fixed.

you can pull latest or gvm:20.08-v2

**Comment by mrod23** [comment]
@dicksnel  do you have to do any additional setup to get the TLS connection going?

**Comment by dicksnel** [comment]
@mrod23 no it works for me with the basic example.

**Comment by mrod23** [comment]
Thanks. Got it going after I posted the message yesterday
