### ISSUE TITLE
Option to disable sync on startup

### ISSUE THREAD

**Issue by david-colombo** [Secure-Compliance-Solutions-LLC/GVM-Docker#108]
**Is your feature request related to a problem? Please describe.**
I have a GVM docker on my laptop to carry it around for quick on-site vulnerability scans.
So the container is not always running and gets only started on purpose.
But due to the fact that it reloads the vulnerability data every time the container (re)starts, it always takes a really long time until the container is up and usable.
In my opinion it takes too long to be really useful for "quick" on-site use.

**Describe the solution you'd like**
Since theres now the possibility to update the vulnerability data with the bash script without restarting I'd love to be able to turn off the vulnerability data update sync after the first initial sync during the first initial startup.

**Comment by disarmm** [comment]
we COULD do this, but then it creates a problem for people first launching the container. They would have no NVTs. If you use a variable, you'd be stuck with that option every time you started the container, which isn't ideal, because if you said no.. then you'd just have to let it run for 12 hours(i think  until the NVT update script runs

we could maybe do something janky like create an nvts.updated file on first launch and then subsequent launches don't update the NVTs unless the file is X days old?

**Comment by david-colombo** [comment]
Well, I think a variable/option would be just right, because if you said no (which you'd only do when you explicitly plan to use it that way) then you'd be able to manually run the bash script also instead of having to let it run for 12 hours.

And a nvts.updated file doesn't make sense because I don't even want to (on startup) update  the NVT's, CERT & SCAP data when they are outdated after X days but rather when I choose to run the sync-all.sh (when I have time to let the container do so).

If there's an "Do not sync data on startup" option/variable:
What about an /initialsync file with similar purpose as the /firstrun file?
Like if the option is set it could touch an /initialsync file after the first initial sync during the first startup and then on following startups check if the /initialsync file is present and then do not run the sync-all.sh script.

**Comment by LandonStewart** [comment]
> ... people first launching the container. They would have no NVTs

Could the option check to see there are NVTs and only disable sync in that case?

**Comment by disarmm** [comment]
@LandonStewart thats what i was suggesting with the nvts.updated file. if the file exists, then it wouldn't try to update on startup unless you changed the variable. For this you'd have to use a docker compose file or you wouldn't be able to change the variable when needed.

We still need to work through this internally and we have some other projects we're finishing. It might be another week or so before this is addressed. We need to figure out a process that works for everyone.

**Comment by david-colombo** [comment]
@disarmm Why would you need a docker compose file for that?
Couldn't there just be a `docker exec -it gvm bash -exec "/toggleSync.sh"` command to switch the option on/off when needed?

**Comment by disarmm** [comment]
that wouldn't update a variable in the container config. You could run the sync on demand that way, but it wouldn't change the container config. Even if your toggleSync.sh script changed your container variables, it would essentially just be a session variable that you lose once you restart the container, which you would need to do to trigger the sync/update.

**Comment by david-colombo** [comment]
It wouldn't change a variable in the container config, absolutely.

But this variable wouldn't be needed then anymore. Imagine that `toogleSync.sh` touches a `/nosync` file and every time a container restarts or automated sync would want to run, it simply checks if the this file is present, if so, do not sync.

If someone wants to "sync on demand" then simply the `sync-all.sh` script could be triggered manually.

And re-enabling sync on startup and automated would be toggling it again, which removes the `/nosync` file.

**Comment by AjaCoder** [comment]
If I understand the request correctly it's already implemented with the AUTO_SYNC var.
Just set it to false and it won't update on startup.
