### ISSUE TITLE
Question: Persistence 

### ISSUE THREAD

**Issue by TheEagle13** [Secure-Compliance-Solutions-LLC/GVM-Docker#11]
What folders/paths do I need to mount if I want to make this deployment persistent? 

Thanks!

**Comment by pixelsquared** [comment]
I am working on adding this information to the readme. Should be added within a few days.

**Comment by pixelsquared** [comment]
I have added information to the readme on how to setup persistence.

**Comment by ctr49** [comment]
Shouldn't
```docker run --detach --publish 8080:9392 -e PASSWORD="Your admin password here" --volume gvm-data:/data --name gvm securecompliance/gvm```
result in data showing up in
```/var/lib/docker/volumes/gvm-data/```?
I can't see anything in there.

**Comment by pixelsquared** [comment]
Are you using the newest version of the container?
You can get the newest version with `docker pull securecompliance/gvm`
