### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by C1ph3R-s** [Secure-Compliance-Solutions-LLC/GVM-Docker#114]
Could you give me a proper docker command where I will not get a blank page in the browser?
Unfortunately I have tried run your container on some ports, but I have always got a blank page.

Thanks,

**Comment by disarmm** [comment]
what start command have you been using?

and are you using https to view the page after you launch?

Are you waiting until the container finishes loading? The NVT feeds seem to be throttled now, so it can take 20-30 minute to do the initial sync

https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/wiki/Checking-Deployment-Progress

**Comment by LandonStewart** [comment]
After starting the container you should watch the logs `docker container logs --follow <containername>`.  You'll see the progress of the startup.  It's likely as @disarmm said and the initial sync's are not finishing.

Eventually you'll see something like this:
```
2020-11-18T21:09:23.647004656Z ++++++++++++++++++++++++++++++++++++++++++++++
2020-11-18T21:09:23.647017040Z + Your GVM 20.04 container is now ready to use! +
2020-11-18T21:09:23.647021208Z ++++++++++++++++++++++++++++++++++++++++++++++
```

After which you should be good to go.  You must use HTTPS though unless you added the following to the service in docker:
```
    environment:
      - ...otherstuff...
      - HTTPS=false
```

**Comment by pixelsquared** [comment]
@C1ph3R-s I am going to close this issue if you still have this problem just add a comment and I will reopen it.
