### ISSUE TITLE
Increase the web timeout #tip

### ISSUE THREAD

**Issue by rudnypc** [Secure-Compliance-Solutions-LLC/GVM-Docker#115]
I change the dockerfile lines 92-103 with this: 
```
RUN mkdir /build && \
    cd /build && \
    wget --no-verbose https://github.com/greenbone/gsa/archive/$gsa_version.tar.gz && \
    tar -zxf $gsa_version.tar.gz && \
	sed -i 's/300000/90000000/g' /build/*/gsa/src/gmp/gmpsettings.js && \
	find /build/ -type f -exec sed -i 's/timeout: 30000/timeout: 9000000/g' {} \; && \
	find /build/ -type f -exec sed -i 's/expect(settings.timeout).toEqual(30000)/expect(settings.timeout).toEqual(9000000)/g' {} \; && \
    cd /build/*/ && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    make && \
    make install && \
    cd / && \
    rm -rf /build
```

Why? I increased the timeout of the GSA and now I can export my reports without errors.

**Comment by pixelsquared** [comment]
Would you consider creating a pull request for your change?

**Comment by rudnypc** [comment]
I saw a pull request stucked, if the conflict is a normal situation, I can learn more about and create a pull request.

**Comment by pixelsquared** [comment]
Here is GitHub's Documentation on creating pull requests:
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests

If you want more help you can join our gitter chat room at: https://gitter.im/Secure-Compliance-Solutions-LLC/gvm-docker
