### ISSUE TITLE
the remote scanner bug

### ISSUE THREAD

**Issue by jweny** [Secure-Compliance-Solutions-LLC/GVM-Docker#116]
I add a remote scanner follow https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/wiki/Setup-Remote-scanner

but when I start a task use the remote scanner, it failed.

![image](https://user-images.githubusercontent.com/26767398/100195473-5a03c980-2f32-11eb-963c-84f078fd7160.png)

**Comment by jweny** [comment]
server ssh log
![image](https://user-images.githubusercontent.com/26767398/100196102-5e7cb200-2f33-11eb-96b2-95cf04e72f65.png)

**Comment by rudnypc** [comment]
@jweny 
https://github.com/Secure-Compliance-Solutions-LLC/OpenVAS-Docker/issues/1
This problem is solved in my issue.

**Comment by jweny** [comment]
tks. but I don`t understand how to do to fix the bug. 
![image](https://user-images.githubusercontent.com/26767398/100301530-49eff680-2fd3-11eb-8bbb-02fce7c15707.png)

**Comment by jweny** [comment]
delete "--scaninfo-store-time 12" ?

**Comment by jweny** [comment]
ok I delete, it runs. ths very much!
