### ISSUE TITLE
Unable to get past login page

### ISSUE THREAD

**Issue by TheEagle13** [Secure-Compliance-Solutions-LLC/GVM-Docker#12]
Pulled the latest version,
Installed with `docker run -d -p 127.0.0.1:9392:9392 --name gvm securecompliance/gvm`

Logs show that login was successful, but I keep getting presented with the login page. I cannot manually navigate to any of the deeper URIs.

Here is the tail of the logs:

`Starting Open Scanner Protocol daemon for OpenVAS...
Starting Greenbone Vulnerability Manager...
Creating Greenbone Vulnerability Manager admin user
User created.
Starting Greenbone Security Assistant...
++++++++++++++++++++++++++++++++++++++++++++++
+ Your GVM 11 container is now ready to use! +
++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++
+ Tailing logs +
++++++++++++++++
==> /usr/local/var/log/gvm/gsad.log <==
gsad main:MESSAGE:2020-02-02 15h51.48 utc:309: Starting GSAD version 9.0

==> /usr/local/var/log/gvm/gvmd.log <==
md manage:WARNING:2020-02-02 15h51.46 utc:285: sql_exec_internal: SQL: CREATE OR REPLACE VIEW vulns AS SELECT id, uuid, name, creation_time, modification_time,        cast (cvss_base AS double precision) AS severity, qod,        'nvt' AS type FROM nvts WHERE uuid IN   (SELECT nvt FROM results     WHERE (results.severity != -3.0)) UNION SELECT id, uuid, name, creation_time, modification_time,       cvss AS severity, 75 AS qod,       'cve' AS type FROM cves WHERE uuid IN   (SELECT nvt FROM results     WHERE (results.severity != -3.0)) UNION SELECT id, uuid, name, creation_time, modification_time,       max_cvss AS severity, 75 AS qod,       'ovaldef' AS type FROM ovaldefs WHERE uuid IN   (SELECT nvt FROM results     WHERE (results.severity != -3.0))
md manage:WARNING:2020-02-02 15h51.46 utc:285: sqlv: sql_exec_internal failed
md manage:   INFO:2020-02-02 15h51.47 utc:289: update_dfn_xml: dfn-cert-2018.xml
md manage:   INFO:2020-02-02 15h51.47 utc:289: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2018.xml
md   main:MESSAGE:2020-02-02 15h51.47 utc:298:    Greenbone Vulnerability Manager version 9.0.0 (DB revision 221)
md manage:   INFO:2020-02-02 15h51.47 utc:298:    Getting users.
md manage:WARNING:2020-02-02 15h51.48 utc:298: database must be initialised from scanner
md   main:MESSAGE:2020-02-02 15h51.48 utc:303:    Greenbone Vulnerability Manager version 9.0.0 (DB revision 221)
md manage:   INFO:2020-02-02 15h51.48 utc:303:    Creating user.
md manage:WARNING:2020-02-02 15h51.48 utc:303: database must be initialised from scanner

==> /usr/local/var/log/gvm/openvas.log <==
lib  nvticache:MESSAGE:2020-02-02 15h50.47 utc:133: Updated NVT cache from version 0 to 202001311108

==> /usr/local/var/log/gvm/ospd-openvas.log <==

==> /usr/local/var/log/gvm/gvmd.log <==
md manage:   INFO:2020-02-02 15h51.51 utc:289: update_dfn_xml: dfn-cert-2010.xml
md manage:   INFO:2020-02-02 15h51.51 utc:289: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2010.xml
md manage:   INFO:2020-02-02 15h51.54 utc:289: update_dfn_xml: dfn-cert-2012.xml
md manage:   INFO:2020-02-02 15h51.54 utc:289: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2012.xml
md manage:   INFO:2020-02-02 15h51.56 utc:288: OSP service has newer VT status (version 202001311108) than in database (version (null), 0 VTs). Starting update ...
md manage:   INFO:2020-02-02 15h51.57 utc:289: update_dfn_xml: dfn-cert-2013.xml
md manage:   INFO:2020-02-02 15h51.57 utc:289: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2013.xml
md manage:   INFO:2020-02-02 15h52.00 utc:289: update_dfn_xml: dfn-cert-2014.xml
md manage:   INFO:2020-02-02 15h52.00 utc:289: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2014.xml
md manage:   INFO:2020-02-02 15h52.03 utc:289: update_dfn_xml: dfn-cert-2017.xml
md manage:   INFO:2020-02-02 15h52.03 utc:289: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2017.xml
md manage:   INFO:2020-02-02 15h52.07 utc:289: update_dfn_xml: dfn-cert-2020.xml
md manage:   INFO:2020-02-02 15h52.07 utc:289: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2020.xml
md manage:   INFO:2020-02-02 15h52.08 utc:289: update_dfn_xml: dfn-cert-2015.xml
md manage:   INFO:2020-02-02 15h52.08 utc:289: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2015.xml
md manage:   INFO:2020-02-02 15h52.11 utc:289: update_dfn_xml: dfn-cert-2008.xml
md manage:   INFO:2020-02-02 15h52.11 utc:289: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2008.xml
md manage:   INFO:2020-02-02 15h52.11 utc:289: update_dfn_xml: dfn-cert-2016.xml
md manage:   INFO:2020-02-02 15h52.11 utc:289: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2016.xml
md manage:   INFO:2020-02-02 15h52.15 utc:289: update_dfn_xml: dfn-cert-2011.xml
md manage:   INFO:2020-02-02 15h52.15 utc:289: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2011.xml
md manage:   INFO:2020-02-02 15h52.18 utc:289: update_dfn_xml: dfn-cert-2019.xml
md manage:   INFO:2020-02-02 15h52.18 utc:289: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2019.xml
md manage:   INFO:2020-02-02 15h52.28 utc:289: Updating /usr/local/var/lib/gvm/cert-data/CB-K20.xml
md manage:   INFO:2020-02-02 15h52.28 utc:289: Updating /usr/local/var/lib/gvm/cert-data/CB-K18.xml
md manage:   INFO:2020-02-02 15h52.31 utc:289: Updating /usr/local/var/lib/gvm/cert-data/CB-K15.xml
md manage:   INFO:2020-02-02 15h52.34 utc:289: Updating /usr/local/var/lib/gvm/cert-data/CB-K16.xml
md manage:   INFO:2020-02-02 15h52.38 utc:289: Updating /usr/local/var/lib/gvm/cert-data/CB-K17.xml
md manage:   INFO:2020-02-02 15h52.42 utc:289: Updating /usr/local/var/lib/gvm/cert-data/CB-K14.xml
md manage:   INFO:2020-02-02 15h52.45 utc:289: Updating /usr/local/var/lib/gvm/cert-data/CB-K13.xml
md manage:   INFO:2020-02-02 15h52.46 utc:289: Updating /usr/local/var/lib/gvm/cert-data/CB-K19.xml
md manage:   INFO:2020-02-02 15h52.49 utc:289: Updating Max CVSS for DFN-CERT
md manage:   INFO:2020-02-02 15h52.50 utc:289: Updating DFN-CERT CVSS max succeeded.
md manage:   INFO:2020-02-02 15h52.50 utc:289: Updating Max CVSS for CERT-Bund
md manage:   INFO:2020-02-02 15h52.50 utc:289: Updating CERT-Bund CVSS max succeeded.
md manage:   INFO:2020-02-02 15h52.50 utc:289: sync_cert: Updating CERT info succeeded.
md manage:   INFO:2020-02-02 15h58.03 utc:288: Updating VTs in database ... 57501 new VTs, 0 changed VTs
md manage:   INFO:2020-02-02 15h58.14 utc:288: Updating VTs in database ... done (57501 VTs).

==> /usr/local/var/log/gvm/gsad.log <==
gsad  gmp:MESSAGE:2020-02-02 16h05.58 utc:310: Authentication success for 'admin' from 172.17.0.1
gsad  gmp:MESSAGE:2020-02-02 16h11.41 utc:310: Authentication success for 'admin' from 172.17.0.1
`

**Comment by pixelsquared** [comment]
I can't seem to reproduce this problem. What browser are you using?

**Comment by TheEagle13** [comment]
Chromium Version 79.0.3945.130 (Developer Build) Fedora Project (64-bit)

**Comment by TheEagle13** [comment]
It does appear to work in Firefox, however. Must be something broken in chromium

**Comment by TheEagle13** [comment]
OH! I figured it out. You cannot login to more than one instance at a time from the same browser. If I login to a second one it logs me out of the first and I cannot log back in until I clear my cache. (Planning to setup in a Dev/Prod scenario, hence the reason for 2 instances.

**Comment by pixelsquared** [comment]
Glad you got it working. I am going to leave this issue open until we add this information to the documentation.
