### ISSUE TITLE
Problem starting the container - rsync error 

### ISSUE THREAD

**Issue by jskyfacts** [Secure-Compliance-Solutions-LLC/GVM-Docker#121]
I have been facing problem while trying to start the container. I have tried the latest and master build too. The container runs for few seconds and then stops. 
**sudo docker exec -it gvm bash**
this gets me into the container and I am thrown out of it after few seconds.
The log currently is giving me following error:-
![image](https://user-images.githubusercontent.com/55120792/101628612-15098800-3a46-11eb-9a2e-274f76fa4eba.png)
This started happening suddenly. The setup worked fine earlier. 
I have made sure that there are no changes on the firewall which would block anything.
PS- This error started happening after I installed apache on the host. But removing it completely didn't help. Not sure if it has something to do with it or its just a coincidence.

**Comment by Akrugerus** [comment]
The feed service was affected as of earlier today, this issue is not with this container 
https://community.greenbone.net/t/general-connection-problems-to-feed-server/7796/15

**Comment by jakelamotta** [comment]
I think it would be good if the container managed to start when the feed service is not responding since now the risk is that the container is down when the scans are scheduled.
