### ISSUE TITLE
A snapshot (.zip file) of the downloaded data (cert, scap, plugins, etc.) could be added in the repo, so that the syncronization would not take 2 days to complete.

### ISSUE THREAD

**Issue by gnikoloudakis** [Secure-Compliance-Solutions-LLC/GVM-Docker#122]
**Is your feature request related to a problem? Please describe.**
As the docker is configured right now, it takes approximately 2 days to finalize the initialization, because the rsync procedure takes a remarkably long time

**Describe the solution you'd like**
Add a snapshot of the latest "/data" folder in .zip format and during the init process, right before the sync-all script,
unzip and sync it with the local "/data" folder. This way the online rsync process won't take forever

**Describe alternatives you've considered**
maybe a different git repo could be created for this purpose. Thus, the script could just git clone the repo (containing a compressed version of the data), avoiding the time consuming rsync

**Additional context**
I have been in the process of testing such a script. So far it looks promising approach. Though the solution is not yet polished enough to create a pull request. It would be great if this feature was adopted officially

**Comment by gnikoloudakis** [comment]
It literally takes more than two whole days to sync!!

**Comment by pixelsquared** [comment]
Just as an update we are working on a method to speed up initial sync times.

**Comment by austinsonger** [comment]
This changed has already been performed. #177
