### ISSUE TITLE
The Greenbone Vulnerability Manager service is not responding. This could be due to system maintenance. Please try again later, check the system status, or contact your system administrator.

### ISSUE THREAD

**Issue by aiaiduo** [Secure-Compliance-Solutions-LLC/GVM-Docker#126]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
I reported this error when I logged in the web page. Docker is running normally, and there is no error message when executing Docker logs container ，I use the image name for securecompliance/GVM: master
![image](https://user-images.githubusercontent.com/28044296/104555649-2d8a4500-5679-11eb-88e8-f1063f7bca86.png)
![image](https://user-images.githubusercontent.com/28044296/104557842-df774080-567c-11eb-93df-0b36528a6949.png)

**Additional context**

**Comment by alexmartinezzz** [comment]
I have the same error after setting up our docker OpenVAS: 
The Greenbone Vulnerability Manager service is not responding. This could be due to system maintenance. Please try again later, check the system status, or contact your system administrator.

How can I check the system status?

**Comment by alexmartinezzz** [comment]
The log files shows this:
gsad  gmp:WARNING:2021-03-11 10h58.08 utc:1306: Authentication failure for 'admin' from 10.10.2.100. Status was 1.

**Comment by thecomet28** [comment]
We are also experiencing the same issue with our scanner. Happens every few days. To temporarily resolve the issue, we have restarted the docker, but this becomes a pain.

**Comment by MParvin** [comment]
I also had this problem. I saw logs of the containers, and according to the log, there is a problem with my PostgreSQL server:
```
greenbone-community-edition-gvmd-1                 | waiting 1 second for ready Postgres container
```

I checked the log of PostgreSQL:
```
docker compose logs pg-gvm
```

and there was a problem with disk space:
```
psql: error: FATAL:  could not write init file
```
maybe it will be helpful for someone who see this page.
