### ISSUE TITLE
Error "scan_run_status" in "Scans > Reports" after migratin from 11.0.1-v1 to 20.08-v1

### ISSUE THREAD

**Issue by carlotodeschini** [Secure-Compliance-Solutions-LLC/GVM-Docker#127]
**Describe the bug**
I'm using v. 11.0.1-v1 since few months with success but upgrading to v. 20.08-v1, when selecting the menu "Scans > Reports" I get this error:

```
TypeError: Cannot read property 'scan_run_status' of undefined

    in mG
    in tbody
    in t
    in styled.tbody
    in table
    in Unknown
    in t
    in Styled(StripedTable)
    in div
    in Unknown
    in t
    in Styled(Layout)
    in n
    in Unknown
    in div
    in Unknown
    in t
    in Layout
    in section
    in tr
    in n
    in div
    in Unknown
    in t
    in Layout
    in n
    in w
    in Unknown
    in n
    in n
    in w
    in withRouter(Connect(n))
    in n
    in Unknown
    in l
    in w
    in Unknown
    in a
    in n
    in Unknown
    in Tg
    in n
    in Unknown
    in w
    in Unknown
    in t
    in t
    in n
    in main
    in t
    in Main
    in Unknown
    in t
    in withLayout(Main)
    in div
    in Unknown
    in t
    in Styled(Layout)
    in n
    in withRouter(n)
    in Unknown
    in n
    in w
    in withRouter(Connect(n))
    in Unknown
    in n
    in w
    in withRouter(Connect(n))
    in Unknown
    in t
    in t
    in Unknown
    in Unknown
    in n
    in w
    in l
    in n
    in n
TypeError: Cannot read property 'scan_run_status' of undefined
    at mG (https://tode:9392/static/js/main.bc743b66.chunk.js:1:1448862)
    at Gi (https://tode:9392/static/js/2.f7d69170.chunk.js:2:684338)
    at bc (https://tode:9392/static/js/2.f7d69170.chunk.js:2:730750)
    at us (https://tode:9392/static/js/2.f7d69170.chunk.js:2:723277)
    at cs (https://tode:9392/static/js/2.f7d69170.chunk.js:2:723202)
    at Zc (https://tode:9392/static/js/2.f7d69170.chunk.js:2:720211)
    at https://tode:9392/static/js/2.f7d69170.chunk.js:2:671596
    at t.unstable_runWithPriority (https://tode:9392/static/js/2.f7d69170.chunk.js:2:747183)
    at Yo (https://tode:9392/static/js/2.f7d69170.chunk.js:2:671305)
    at Vo (https://tode:9392/static/js/2.f7d69170.chunk.js:2:671541)
```

**To Reproduce**
1. change image version from "securecompliance/gvm:11.0.1-v1" to "securecompliance/gvm:20.08-v1" (same behaviour switching to "gvm:20.08-v2")
2. run image with docker command (maintaining your previous "data" dir)
3. all seems to work without issues
4. select menu "Scans > Reports" to get the error

**Expected behavior**
A list of recent reports

**Screenshots**
![gvm_screenshot](https://user-images.githubusercontent.com/4517111/105227928-32ac3000-5b62-11eb-9673-5dabac65ec2f.png)

How to fix?

**Comment by pixelsquared** [comment]
We have also encountered this issue and are working to solve it.

**Comment by pixelsquared** [comment]
As a quick test could you delete the file "created_gvm_user" in the data volume for the container and restart it?

**Comment by pixelsquared** [comment]
I believe that will fix the issue. You may have to wait about 15 minutes after it restarts for the reports to import.

**Comment by markdesilva** [comment]
After deleting "created_gvm_user" and restarting, it says:

Creating Greenbone Vulnerability Manager admin user
User exists already.

then the whole container stops and exits. 

Re-touched "created_gvm_user" and restarted, still error with reports. Waited 15-20 mins, still error.

Went into the container and manually did this:

USERSLIST=$(su -c "gvmd --get-users --verbose" gvm); IFS=' '; read -ra ADDR <<<"$USERSLIST"; echo "${ADDR[1]}"; su -c "gvmd --modify-setting 78eceaec-3385-11ea-b237-28d24461215b --value ${ADDR[1]}" gvm

Then restarted container. Waited 20 mins - still error.
```

TypeError: s is undefined


    in mG
    in tbody
    in t
    in styled.tbody
    in table
    in Unknown
    in t
    in Styled(StripedTable)
    in div
    in Unknown
    in t
    in Styled(Layout)
    in n
    in Unknown
    in div
    in Unknown
    in t
    in Layout
    in section
    in tr
    in n
    in div
    in Unknown
    in t
    in Layout
    in n
    in w
    in Unknown
    in n
    in n
    in w
    in withRouter(Connect(n))
    in n
    in Unknown
    in l
    in w
    in Unknown
    in a
    in n
    in Unknown
    in Tg
    in n
    in Unknown
    in w
    in Unknown
    in t
    in t
    in n
    in main
    in t
    in Main
    in Unknown
    in t
    in withLayout(Main)
    in div
    in Unknown
    in t
    in Styled(Layout)
    in n
    in withRouter(n)
    in Unknown
    in n
    in w
    in withRouter(Connect(n))
    in Unknown
    in n
    in w
    in withRouter(Connect(n))
    in Unknown
    in t
    in t
    in Unknown
    in Unknown
    in n
    in w
    in l
    in n
    in n

mG@https://secscan.bic.nus.edu.sg:4000/static/js/main.bc743b66.chunk.js:1:1448860
Gi@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:684338
bc@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:730750
us@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:723279
cs@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:723202
Zc@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:720211
Vo/<@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:671596
t.unstable_runWithPriority@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:747183
Yo@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:671305
Vo@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:671543
Uo@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:671476
es@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:720502
notify@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:29000
u</t.notifyNestedSubs@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:29635
u</t.handleChangeWrapper@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:29703
b@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:115881
r/</</<@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:517001
dispatch@https://secscan.bic.nus.edu.sg:4000/static/js/2.f7d69170.chunk.js:2:119649
u/</</</<@https://secscan.bic.nus.edu.sg:4000/static/js/main.bc743b66.chunk.js:1:54064
```

**Comment by markdesilva** [comment]
Can't get scans to run either:

```
md manage:WARNING:2021-01-24 01h27.51 +08:4676: Could not connect to Scanner at /tmp/ospd.sock
md manage:WARNING:2021-01-24 01h27.51 +08:4676: OSP start_scan 6d18717d-2a33-4cd9-81dd-146ef9223297: Could not connect to Scanner
```

Seeing this in the logs too:

`md manage:WARNING:2021-01-24 01h27.15 +08:4579: run_report_format_script: No generate script found at /usr/local/var/lib/gvm/gvmd/report_formats/generate`

**Comment by pixelsquared** [comment]
@markdesilva I think you may have a different issue.

**Comment by markdesilva** [comment]
> @markdesilva I think you may have a different issue.

Hi, how so? 

To confirm the update from 11 to 20.04

1) pull the latest image
2) stop current image
3) delete current image
4) start latest image with same docker command and options as detailed in gitbook:

`docker run --detach --publish 8080:9392 --publish 5432:5432 --publish 2222:22 --env DB_PASSWORD="postgres DB password" --env PASSWORD="webUI password" --volume gvm-data:/data --name gvm securecompliance/gvm`

Correct?

**Comment by pixelsquared** [comment]
That should be correct. There is definitely something wrong with the upgrade process. I think your scanner not connecting might be different but not 100% sure. But you are right the "No generate script found" message is the same as this issue.

**Comment by markdesilva** [comment]
Thanks for the confirmation. Could you explain how removing the created_gvm_user fixes the issue? From what I can see from the start.sh script it just does creation of the user and adds the unique id?

Apologies for all the questions, I’m a little out of my depth here. 

Thank you.

**Comment by pixelsquared** [comment]
This might be easier to talk about in the gitter chat.

**Comment by carlotodeschini** [comment]
> I believe that will fix the issue. You may have to wait about 15 minutes after it restarts for the reports to import.

Sorry but this doesn't solve my issue.

I've created a docker-compose.yaml file and after a "up" it ends into a never ending loop startup.

```
[...]
itss_gvm | Starting Greenbone Vulnerability Manager...
itss_gvm | Waiting for Greenbone Vulnerability Manager to finish startup...
itss_gvm | admin
itss_gvm | Creating Greenbone Vulnerability Manager admin user
itss_gvm | User exists already.
itss_gvm exited with code 1
itss_gvm | Testing redis status...
itss_gvm | Redis ready.
itss_gvm | Starting PostgreSQL...
[...]
```

So I restored the "created_gvm_user" file and reverted back to the old image.

I also tried to follow this [thread](https://community.greenbone.net/t/fix-for-reports-not-displaying-in-gvm-20-8-due-to-javascript-errors/7905) but I think permissions are OK in our image; @pixelsquared can you check please?

Thanks for the support,
tode

**Comment by carlotodeschini** [comment]
To add another info for this issue I get the following error when I try to access to the reports page:

`itss_gvm | md manage:WARNING:2021-01-26 07h44.27 UTC:1426: run_report_format_script: No generate script found at /usr/local/var/lib/gvm/gvmd/report_formats/generate`

repeated 10 times.

I hope this help,
tode

**Comment by markdesilva** [comment]
I gave up. Ran a brand new install of the latest pull on a new machine and manually keyed in all my notes, overrides, targets, tasks, schedules, etc. took a whole day! So starting 2021 scans with clean backend.

Downloaded all the 100s of past full reports in pdf and xml formats.

**Comment by pixelsquared** [comment]
I have managed to get a upgraded version to work. I am now working on an update to the start.sh shell script to fix this issue.

**Comment by markdesilva** [comment]
Hahaha after all the work I did to manually add in my overrides, tasks ,etc! 

*thumbs up*

> I have managed to get an upgraded version to work. I am now working on an update to the start.sh shell script to fix this issue.

**Comment by carlotodeschini** [comment]
@pixelsquared : any update on this issue?
thanks

**Comment by pixelsquared** [comment]
@carlotodeschini sorry about the delay some other stuff came up but I can get back to this now and should have some updates soon.

**Comment by pixelsquared** [comment]
Hi everyone,

This problem is more complex than I first thought because of how I first setup the container.
My question is can you live with just for this version requiring that a fresh install is used?
I know this is not ideal but the time required to fix this issue is taking time away from other issues.
So I want to understand how important this issue is to different people.

**Comment by markdesilva** [comment]
Well I lived with a fresh install and I’m still using it, I just looked at it as starting a fresh year clean. I still have all the old reports and if absolute necessary I can fire up the vm with the v11 and refer to stuff there. 

That said, that is only me. I suspect others might not be able to live with it. However I think the memory leak issue is more pressing? Has that be addressed?

**Comment by carlotodeschini** [comment]
> My question is can you live with just for this version requiring that a fresh install is used?

I need to upgrade to v. 20 because v. 11 reports are now full of "NVT: Report outdated / end-of-life Scan Engine / Environment (local)" red alert.

I there a guide/howto to help me to migrate v. 11 data to v. 20 fresh install? 

Or can I try to help you to catch and solve the problem?
