### ISSUE TITLE
Problem when generate pdf report larger than 1Mo and send it by email

### ISSUE THREAD

**Issue by fredericpougnault** [Secure-Compliance-Solutions-LLC/GVM-Docker#128]
I solve this problem by start gvmd like this :
su -c "gvmd --listen=0.0.0.0 --port=9390  --max-email-attachment-size="-1" --max-email-include-size="-1" --max-email-message-size="-1"" gvm

I modified my start.sh script with the line above

**Comment by austinsonger** [comment]
Added this to the documentation https://github.com/Secure-Compliance-Solutions-LLC/gitbook/blob/master/openvas-greenbone-deployment-full-guide/faq.md
