### ISSUE TITLE
Question: Does anyone know how to pull down the report format ids?

### ISSUE THREAD

**Issue by mrod23** [Secure-Compliance-Solutions-LLC/GVM-Docker#132]
Trying to pull down report format ids using python-gvm 

I'm not getting anything back when running this function gvm.get_report_formats()

My goal is to export the results via this command: 

report = gmp.get_report(report_id=task_report_id, details=True, report_format_id="c1645568-627a-11e3-a660-406186ea4fc5" )

The reports are loaded onto the Docker container
Anyone else having this issue?

`root@openvas-5c6d56797-bg8fr:/# ls data/gvmd/report_formats/
5057e5cc-b825-11e4-9d0e-28d24461215b  910200ca-dc05-11e1-954f-406186ea4fc5  a994b278-1f62-11e1-96ac-406186ea4fc5
50c9950a-f326-11e4-800c-28d24461215b  9ca6fe72-1f62-11e1-9e7c-406186ea4fc5  c15ad349-bd8d-457a-880a-c7056532ee15
5ceff8ba-1f62-11e1-ab9f-406186ea4fc5  9e5e5deb-879e-4ecc-8be6-a71cd0875cdd  c1645568-627a-11e3-a660-406186ea4fc5
77bd6c4a-1f62-11e1-abf0-406186ea4fc5  a3810a62-1f62-11e1-9219-406186ea4fc5  c402cc3e-b531-11e1-9163-406186ea4fc5
9087b18c-626c-11e3-8892-406186ea4fc5  a684c02c-b531-11e1-bdc2-406186ea4fc5l`

*

**Comment by Dexus** [comment]
@mrod23 did your container run a bit longer than 5 minutes when you test it? Because if gvmd is not full synced you will never get any data back. The container must run and the configs all loaded (gvmd need some time after the sync of all data, on fresh installations. So maybe after the webinterface is reachable it take another 5-20 minutes.

**Comment by Dexus** [comment]
@mrod23 if you already found your issue, please close this issue. Or I will do this by next weekend. 
Thank you for your cooperation.

**Comment by Dexus** [comment]
BTW: 
```shell
# install gvm-tools
#example in gvm container
gvm-cli --gmp-username admin --gmp-password <password> [--host <gvmd>] --protocol gmp tls '--xml=<get_report_formats/>'
```
This should give you everything you need.

**Comment by mrod23** [comment]
Closing this out
