### ISSUE TITLE
Please update spelling

### ISSUE THREAD

**Issue by bjoernricks** [Secure-Compliance-Solutions-LLC/GVM-Docker#14]
Hi,

the spelling is Greenbone and not camel cased GreenBone. Could you do me a favor and update all texts accordingly?

Regards

**Comment by pixelsquared** [comment]
The capitalization for Greenbone has been fixed in the readme.
I belive the only place the it was camel cased was in the title of the readme.

**Comment by bjoernricks** [comment]
Thanks!
