### ISSUE TITLE
 gvmd: Waiting for incoming connections

### ISSUE THREAD

**Issue by Ajeeshb** [Secure-Compliance-Solutions-LLC/GVM-Docker#142]
I have started my Openvas container using the below docker image.

> securecompliance/gvm   latest              fb51bb84ef57        7 days ago          2.47GB
`docker run --detach --publish 8080:9392 --publish 5432:5432 --publish 2222:22 --env DB_PASSWORD="xx" --env PASSWORD="xx" --volume gvm-data:/data --name gvm securecompliance/gvm`

After adding the host machine i have started my scan and it is showing 0% status all the time. and while checking in the container i am seeing the following.

> ==> /usr/local/var/log/gvm/gvmd.log <==
> event task:MESSAGE:2021-03-05 10h11.24 UTC:21198: Status of task Openvas-Server (axx0f5-4c33-aa92-a5xx0c) has changed to Running

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                   
 1249 gvm       20   0  231048 116780   8152 S   0.3   2.3   1:48.61 gvmd: Waiting for incoming connections 
```

So my scanning is not working and all the time it is showing 0%

**Comment by Ajeeshb** [comment]
![image](https://user-images.githubusercontent.com/11266795/110106041-2d800900-7dcf-11eb-9063-af24ef4c871f.png)

**Comment by austinsonger** [comment]
Did you only build and deploy this once? If yes, then can you try doing it again.

What operating system you using?

**Comment by Ajeeshb** [comment]
My docker host is running on Ubuntu 14.04.5 LTS
