### ISSUE TITLE
Adding HTTPS

### ISSUE THREAD

**Issue by dagostoo** [Secure-Compliance-Solutions-LLC/GVM-Docker#15]
Hey! Can you please explain how to add nginx as reverse proxy? I need gvm on https, not http. In your container it is http only. Thanks!

**Comment by dagostoo** [comment]
Okay, I saw one more closed similar issue. Have you worked on adding HTTPS support? Your container is very good, up and running, but we need HTTPS support badly..

**Comment by pixelsquared** [comment]
How would you like HTTPS support to work?

**Comment by pixelsquared** [comment]
Self-signed cert, Add your own, Letsencrypt, etc

**Comment by petrojak** [comment]
Https support would be amazing, especially if i could add my own certificate.

**Comment by rux616** [comment]
> Self-signed cert, Add your own, Letsencrypt, etc

I would say start with a self-signed cert to get the ball rolling, and expand from there based on feedback.

**Comment by ciscoqid** [comment]
I just spun up nginx on the host system proxied via the default 8080 port, but having it builtin would be nice!

**Comment by ciscoqid** [comment]
Another option as a general fix within the container is to run "gvm-manage-certs -a" as part of system initialization.

**Comment by petrojak** [comment]
> Another option as a general fix within the container is to run "gvm-manage-certs -a" as part of system initialization.

yes this sets up the certificates but i belive you also need to change how gsad starts. In start.sh 'su -c "gsad --verbose --http-only --no-redirect --port=9392"' is used to start gsad (as you can see its http-only). You need to run something like this 'su -c "gsad -v -p 9392 -r 9391" gvm' to allow https. I am not 100% sure about the command right now, as i cannot find my altered startup script.

**Comment by rvanero** [comment]
should look into jwilder nginx or standard nginx docker image, i got it working via https. This a very nice docker image, tho will probably raise a possible enhancement to update nvt's or other records without restarting the docker container itself

**Comment by DocSnyd3r** [comment]
Hi,
I use these compose files. Certs go simply into the nginx-certs folder with the hostname as cert name.

#gvm yml file
docker-compose.yml
version: '3'

services:
  gvm-app:
    image: securecompliance/gvm 

    volumes:
      - gvm-data:/data

    container_name: gvm

    restart: unless-stopped

    expose:
      - "9392"

    environment:
      - VIRTUAL_HOST=somehostname, somehostname.fqdn
      - VIRTUAL_PORT=9392
      - PASSWORD=Password1234

volumes:
  gvm-data:

networks:
  default:
    external:
      name: nginx

the nginx yml
version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './nginx-certs:/etc/nginx/certs:ro'
    restart: always

networks:
  default:
    external:
      name: nginx

**Comment by pixelsquared** [comment]
I am going to close this issue if anyone has ideas or bugs with https please open a new issue.
