### ISSUE TITLE
Remote Scanner GVMLibs Outdated at 20.8.0

### ISSUE THREAD

**Issue by markdesilva** [Secure-Compliance-Solutions-LLC/GVM-Docker#159]
**Describe the bug**
Remote scanner gvmlibs are outdated at 20.8.0. Need to update to 20.8.1

**To Reproduce**
1. Start any scan and wait for it to finish
2. See scan results and "high" severity vulnerability

**Expected behavior**
No "high" severity vulnerability regarding scanner lib being outdated

**Additional context**
Getting this error on my scans from the remote scanner:

```
Vulnerability: Report outdated / end-of-life Scan Engine / Environment (local)

Summary
This script checks and reports an outdated or end-of-life scan   engine for the following environments:

  - Greenbone Source Edition (GSE)

  - Greenbone Security Manager TRIAL (formerly Greenbone Community Edition (GCE))

  used for this scan.

  NOTE: While this is not, in and of itself, a security vulnerability, a severity is reported to
  make you aware of a possible decreased scan coverage or missing detection of vulnerabilities on
  the target due to e.g.:

  - missing functionalities

  - missing bugfixes

  - incompatibilities within the feed
Detection Result

Installed GVM Libraries (gvm-libs) version:        20.8.0
Latest available GVM Libraries (gvm-libs) version: 20.8.1
```

Main scanner is at 20.8.1 already but still getting the above complaint.

**Comment by austinsonger** [comment]
[New Release](https://github.com/Secure-Compliance-Solutions-LLC/OpenVAS-Docker/releases/tag/21.4.0)

**Comment by pixelsquared** [comment]
With the latest release this issue should be fixed

**Comment by thecomet28** [comment]
You need to recompile the docker image. Its still on 20.8.0.

**Comment by pixelsquared** [comment]
@thecomet28 did you pull the new version with docker pull?

**Comment by markdesilva** [comment]
When I pulled “latest” I still got the old version. Had to pull “master” to get the new version.
