### ISSUE TITLE
[Bug]manage_send_report: No such file or directory

### ISSUE THREAD

**Issue by hankyzz** [Secure-Compliance-Solutions-LLC/GVM-Docker#175]
**Describe the bug**
use lastest docker install the gvm11(2021-05-07), when use the reports the error occurred
so i have no idea about it .

**To Reproduce**
1. Go to Scans-Reports
2. See error: 'An internal error occurred while getting resources list. The current list of resources is not available. Diagnostics: Failure to receive response from manager daemon.'
3. Go to Scans->Tasks
4. Click the Last Report "TimeStamp"
5. See error：‘Error while loading Report 745d89ce-73a0-4bbf-86f0-67c528b3df8b
Please try again.’
6、In the container，tail /usr/local/var/log/gvm/gvmd.log
7、See the Warning “ manage_send_report: No such file or directory”

**Screenshots**
eg.
![image](https://user-images.githubusercontent.com/9695206/117529695-89535200-b00b-11eb-8587-a3dd7925acf7.png)
eg.
![image](https://user-images.githubusercontent.com/9695206/117529702-98d29b00-b00b-11eb-92ce-b53e3f787b3a.png)
eg.
![image](https://user-images.githubusercontent.com/9695206/117529709-a720b700-b00b-11eb-840e-6b9cdaa6dffc.png)

**Comment by BobNiko** [comment]
![image](https://user-images.githubusercontent.com/14791058/117817296-1f87b200-b270-11eb-9695-4e0f3c9887fa.png)
I had a similar issue on 21.4.0-v2

**Comment by hankyzz** [comment]
GVM Versions
![image](https://user-images.githubusercontent.com/9695206/117909752-6a0b3c00-b30d-11eb-85f7-8e20148f6032.png)
Operating system:CentOS Linux release 7.4.1708 (Core) Via Docker Images
Command:docker pull securecompliance/gvm【2021-05-07】

**Comment by JoeyChen-NTUT** [comment]
> Are any of you who are experiencing this issue using an upgraded container and if so which version?

I been tested with container upgrade or grant new container had same issue

**Comment by JoeyChen-NTUT** [comment]
this container witch after upgraded sha256:02dda3e23baef5c9d6f6cfe0140033b1881d3f99ec1801abe0a2b6c8a29d3ef1  
![image](https://user-images.githubusercontent.com/40187978/117924323-23770b00-b328-11eb-9735-5e52ae78967e.png)

this container is brand new with latest image still shows issue
![image](https://user-images.githubusercontent.com/40187978/117924323-23770b00-b328-11eb-9735-5e52ae78967e.png)

**Comment by leewan555** [comment]
I have a same problem.
![image](https://user-images.githubusercontent.com/57163495/117925664-2410a100-b32a-11eb-9922-2dfc8cb0d30e.png)

and versions
![image](https://user-images.githubusercontent.com/57163495/117925784-4efaf500-b32a-11eb-8532-c5c3140d7cfc.png)

**Comment by pixelsquared** [comment]
I am having trouble reproducing this issue.

What version of docker? `docker version`

What Linux Distribution and Version?

Are you reusing a volume from an old version?

Try to change `--volume gvm-data:/data` to something like `--volume gvm-data-new:/data` in your docker run to use a new fresh volume.

**Comment by hankyzz** [comment]
**docker --version**
Docker version 1.13.1, build 7d71120/1.13.1
**cat /etc/redhat-release**
CentOS Linux release 7.4.1708 (Core)
**uname -a**
Linux xxxxx 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
**Get Images**
docker pull securecompliance/gvm
**docker run command**
docker run -d -p 8080:9392 -p 2222:22 --name gvm securecompliance/gvm

**Comment by JoeyChen-NTUT** [comment]
> I am having trouble reproducing this issue.
> 
> What version of docker? `docker version`
> 
> What Linux Distribution and Version?
> 
> Are you reusing a volume from an old version?
> 
> Try to change `--volume gvm-data:/data` to something like `--volume gvm-data-new:/data` in your docker run to use a new fresh volume.

I used latest of docker image without any external/persistent volume

![image](https://user-images.githubusercontent.com/40187978/118070134-ebc79c00-b3d7-11eb-9476-e7629d5def37.png)
![image](https://user-images.githubusercontent.com/40187978/118070167-fbdf7b80-b3d7-11eb-930c-e77d8e86ab2c.png)

**Comment by leewan555** [comment]
> What version of docker? `docker version`

**Docker version 19.03.11**

> What Linux Distribution and Version?

**CentOS Linux release 7.7.1908 (Core)**

> Are you reusing a volume from an old version?

**command:**
**docker pull securecompliance/gvm
docker run -d -p 9392:9392 --name gvm -v gvm-data:/data securecompliance/gvm**

**Comment by BobNiko** [comment]
Hey, guys! Are there any updates?
Thanks in advance!

**Comment by austinsonger** [comment]
> Hey, guys! Are there any updates?
> Thanks in advance!

We haven't been able to reproduce this error. But I'm using ubuntu host, so it is looking to be related Centos. Will continue to research.

**Comment by JoeyChen-NTUT** [comment]
> > Hey, guys! Are there any updates?
> > Thanks in advance!
> 
> We haven't been able to reproduce this error. But I'm using ubuntu host, so it is looking to be related Centos. Will continue to research.

It's the same environment with docker container still can't reproduce this error??
in my use case I'm running container in CentOS and I still has same issue even recreate the new container with latest image

**Comment by pixelsquared** [comment]
I am wondering if the report formats are not downloading correctly.
Can you take a screenshot of the "Feed Status" page under "Administration".

**Comment by JoeyChen-NTUT** [comment]
> I am wondering if the report formats are not downloading correctly.
> Can you take a screenshot of the "Feed Status" page under "Administration".

FYI, If need any information just let me know. I'll upload screenshot ASAP.

![image](https://user-images.githubusercontent.com/40187978/119597357-6dc1b700-be13-11eb-83c8-e7fbe54c2139.png)
![image](https://user-images.githubusercontent.com/40187978/119597368-75815b80-be13-11eb-9074-1f792f49d81c.png)
![image](https://user-images.githubusercontent.com/40187978/119597322-5da9d780-be13-11eb-93e8-314161538510.png)
![image](https://user-images.githubusercontent.com/40187978/119596740-5635fe80-be12-11eb-9f67-cc0facc43e38.png)
![image](https://user-images.githubusercontent.com/40187978/119596776-62ba5700-be12-11eb-880b-866703b1795f.png)

**Comment by pixelsquared** [comment]
Something seems to be blocking the reports from running in `/tmp` is there any software that you are using that could cause that?

**Comment by JoeyChen-NTUT** [comment]
> Something seems to be blocking the reports from running in `/tmp` is there any software that you are using that could cause that?

It's fresh install of docker container without any file, folder or volume mapping

**Comment by JoeyChen-NTUT** [comment]
CentOS 7 after update all packet fixed this problem
problem maybe cause by
https://bugzilla.redhat.com/show_bug.cgi?id=1764152
I found out if ls -al inside container will seen the same issue
so I try update all packet to 
![image](https://user-images.githubusercontent.com/40187978/120152265-db108600-c21f-11eb-8560-6f910c092cd8.png)
problem fixed

**Comment by leewan555** [comment]
> CentOS 7 after update all packet fixed this problem
> problem maybe cause by
> https://bugzilla.redhat.com/show_bug.cgi?id=1764152
> I found out if ls -al inside container will seen the same issue
> so I try update all packet to
> ![image](https://user-images.githubusercontent.com/40187978/120152265-db108600-c21f-11eb-8560-6f910c092cd8.png)
> problem fixed

I use CentOS Linux release 7.7.1908 (Core)
Docker version 20.10.6

I tried your solution, and I fix this problem, too!
thanks!

![image](https://user-images.githubusercontent.com/57163495/120174504-bf18de80-c237-11eb-9cce-d0e47d58e13d.png)

![image](https://user-images.githubusercontent.com/57163495/120174954-423a3480-c238-11eb-9825-077bbca5ee4f.png)
