### ISSUE TITLE
[Bug] Bad LDAP Cert Crashes Container When Uploading

### ISSUE THREAD

**Issue by mattjamesaus** [Secure-Compliance-Solutions-LLC/GVM-Docker#194]
**Describe the bug**
When uploading a bad/incorrect LDAP certificate if it's in the wrong format it results in the container silently crashing i.e the container is still "running" but the web interface etc will no longer load upon refresh and will refuse to take anymore requests.

**To Reproduce**
1. Spin up container
2. Login to GVM dashboard
3. Visit settings LDAP
4. Enter valid LDAP server but bad CA.crt e.g binary file.

**Expected behavior**
LDAP configuration should be rejected and user able to upload a different cert / resubmit.

**Screenshots**

**Host Device:**
 - OS: Docker / Amazon Linux 2
 - Version: 21.4.0-v5

**Comment by austinsonger** [comment]
@mattjamesaus do you have any screenshots or logs?

**Comment by Dexus** [comment]
This is not a bug of this container image, please open this bug on @greenbone repo for gsa repo.
