### ISSUE TITLE
Webinterface with own certificate

### ISSUE THREAD

**Issue by jonasdlm** [Secure-Compliance-Solutions-LLC/GVM-Docker#195]
**Is your feature request related to a problem? Please describe.**
No, this is just a feature request.

**Describe the solution you'd like**
The possibility to use our own certificate to avoid the security error when ussing the webinterface with the self signed certificate.
Something like this:

```
KEY={$KEY}
CERT={*CERT}
...
echo "Starting Greenbone Security Assistant..."
if [ -n "$CERT" ]
su -c "gsad --verbose --ssl-certificate=$CERT --ssl-private-key=$KEY --timeout=$TIMEOUT --no-redirect --mlisten=127.0.0.1 --mport=9390 --port=9392" gvm
elif [ $HTTPS == "true" ]; then	
su -c "gsad --verbose --gnutls-priorities=SECURE128:-AES-128-CBC:-CAMELLIA-128-CBC:-VERS-SSL3.0:-VERS-TLS1.0 --timeout=$TIMEOUT --no-redirect --mlisten=127.0.0.1 --mport=9390 --port=9392" gvm
else	
su -c "gsad --verbose --http-only --timeout=$TIMEOUT --no-redirect --mlisten=127.0.0.1 --mport=9390 --port=9392" gvm
fi
```

Certificate can be created en posted in the correct folder (/data/certs/gsad?) after a first start. Afterwards the container can be restarted with the CERT (/data/cert/gsad/cert.cert) and KEY (/data/cert/gsad/key.key) definned.

**Additional context**
I have not tested this yet. Maybe I do when I found some time.

**Comment by austinsonger** [comment]
@pixelsquared

**Comment by Dexus** [comment]
Will add the possibility. Think tomorrow or Monday at the latest, the PR should be there.
