### ISSUE TITLE
[Bug] Web page login error reported This “An error occurred during making the request. Most likely the web server does not respond.”

### ISSUE THREAD

**Issue by aiaiduo** [Secure-Compliance-Solutions-LLC/GVM-Docker#196]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Web page login error reported This “An error occurred during making the request. Most likely the web server does not respond.”,But the page is open and the logs are available。
version:securecompliance/gvm:21.4.0-v5
![image](https://user-images.githubusercontent.com/28044296/120570501-e0054d80-c44a-11eb-9678-3a7278b9f66d.png)
![image](https://user-images.githubusercontent.com/28044296/120570439-b9dfad80-c44a-11eb-8ebb-2ec7ad48630b.png)

**Additional context**

**Comment by austinsonger** [comment]
Usually if you just reload the page, it will fix this.

**Comment by aiaiduo** [comment]
> Usually if you just reload the page, it will fix this.

I modified the local mapping directory of Docker and then re-published it. I suspect the reason is that the name of the directory where data is mapped to the native is too long.，THKS！
