### ISSUE TITLE
When I opened the login page, the error message was "ERR_EMPTY_RESPONSE"

### ISSUE THREAD

**Issue by aiaiduo** [Secure-Compliance-Solutions-LLC/GVM-Docker#197]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

When I opened the login page, the error message was "ERR_EMPTY_RESPONSE". However, my docker was running, and port 8080 was also in normal monitoring state. After the container was restarted, normal login was possible, but this error appeared after a period of operation. What do I need to do to troubleshoot this problem, THKS!

![image](https://user-images.githubusercontent.com/28044296/121105288-69939180-c836-11eb-8508-c8d447c659ff.png)

**Additional context**

**Comment by aiaiduo** [comment]
> Make sure you are using `https://[GVM IP]:8080` and not http.
I started the container with the following parameters：
docker run --detach --publish 8080:9392  --env USERNAME="admin"  --env PASSWORD="123456"  --env  RELAYHOST="smtp"  --env SMTPPORT=25 --env AUTO_SYNC=true  --env HTTPS=false  --env TZ="UTC" --volume /gvm-data:/data  --name gvm  --restart=always  securecompliance/gvm:21.4.0-v5
so,I did not use HTTPS, but HTTP to access the container. When I just started the container, I used HTTP to log in normally and perform the scanning task. However, after several hours of operation, the container would report an error as shown in the title

**Comment by austinsonger** [comment]
#198

**Comment by Dexus** [comment]
@aiaiduo did you test to use a other docker volume?

Problem may that the services inside the container die, and currently not monitored. A fix for this, will be in the `dev` branch but then you also have to use other volumes.

Did you noticed any OOM on you HV? Or did you look into the container and the logs from the services?
