### ISSUE TITLE
When I opened the login page, the error message was "ERR_EMPTY_RESPONSE". [Enhancement

### ISSUE THREAD

**Issue by aiaiduo** [Secure-Compliance-Solutions-LLC/GVM-Docker#198]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
gvm verision：21.4.0-v5 
docker version：20.10.7

When I opened the login page, the error message was "ERR_EMPTY_RESPONSE". However, my docker was running, and port 8080 was also in normal monitoring state. After the container was restarted, normal login was possible, but this error appeared after a period of operation. What do I need to do to troubleshoot this problem, THKS!

![image](https://user-images.githubusercontent.com/28044296/121105537-e0c92580-c836-11eb-99d0-a2b1e1e52055.png)

![image](https://user-images.githubusercontent.com/28044296/121105636-0bb37980-c837-11eb-8899-66f6bc0252aa.png)

**Additional context**

**Comment by austinsonger** [comment]
@pixelsquared
