### ISSUE TITLE
xml_split not found

### ISSUE THREAD

**Issue by 0x646e78** [Secure-Compliance-Solutions-LLC/GVM-Docker#20]
Trying to run as per the instructions on Docker Hub, logs report `sh: 1: xml_split: not found` and then the container exits.

`docker run --detach --publish 8080:9392 -e PASSWORD="somepassword" --name gvm securecompliance/gvm`

```
Creating Greenbone Vulnerability Manager database
CREATE ROLE
GRANT ROLE
CREATE EXTENSION
Creating gvmd folder...
Updating NVTs...
Updating CERT data...
Updating SCAP data...
Starting Open Scanner Protocol daemon for OpenVAS...
Starting Greenbone Vulnerability Manager...
Creating Greenbone Vulnerability Manager admin user
sh: 1: xml_split: not found

```

**Comment by ciscoqid** [comment]
https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/pull/22 added, hopefully enough to fix...

**Comment by pixelsquared** [comment]
@0x646e78 Could you check if the latest container update fixes this issue for you?

**Comment by ciscoqid** [comment]
I confirmed xml_split is now available within the container.

**Comment by 0x646e78** [comment]
@pixelsquared yes, works now thanks.
