### ISSUE TITLE
[Bug] authorized_keys: No such file or directory

### ISSUE THREAD

**Issue by smileitjc** [Secure-Compliance-Solutions-LLC/GVM-Docker#203]
**Describe the bug**
When using ./add-scanner.sh to create a remote scanner on the host, I get the error "./add-scanner.sh: line 12: /data/scanner-ssh-keys/authorized_keys: No such file or directory".

**To Reproduce**
1. run command "docker exec -it gvm ./add-scanner.sh
2. Input scanner Name
3. Input scanner ID
4. Input scanner Public Key
5. See Error.

**Expected behavior**
The scanner is added, but I am getting the below on the remote scanner I presume because the key isn't being saved and therefore isn't an authorized key:

On the remote scanner:
==> /usr/local/var/log/gvm/ssh-connection.log <==
Permission denied, please try again.
Permission denied, please try again.
gvm@192.168.x.x: Permission denied (publickey,password).

**Host Device:**
 - OS: Ubuntu 
 - Version: 20.04 LTS

**Additional context**
Command used to add remote scanner:

docker run --detach --volume scanner:/data --env MASTER_ADDRESS=192.168.[removed].[removed] --env MASTER_PORT=22 --name scanner securecompliance/openvas
8f1ef9729a338983b2858a288b65ac23c5354c32aab2269789742d57bc016ade

**Comment by Dexus** [comment]
Fixed via https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/commit/7378f27cd6d3dfebad6f8ae97c5bab92baa47975

Will also fixed via #213
