### ISSUE TITLE
Dead Hosts Being Scanned

### ISSUE THREAD

**Issue by markdesilva** [Secure-Compliance-Solutions-LLC/GVM-Docker#211]
Hi, I'm not sure if I'm doing it right, but what I'm seeing is that a subnet with only 17 alive hosts is taking over 12 hours to complete.

Checking the logs and the ps output during the scans shows that the scanner is doing a vulnerability scan on the dead hosts.

Any help appreciated.

**Comment by austinsonger** [comment]
Have you tried playing with the scan config?

**Comment by markdesilva** [comment]
Hi,

Yes I have. No options I can see on determining the alive hosts. The only alive options are in the target when setting how to determine if a target is alive. All options still end up scanning dead hosts. 

Thank you.

**Comment by Dexus** [comment]
This is not a problem of this Image. You should run a Discovery Scan and then scan the discovered systems.

**Comment by markdesilva** [comment]
Ok, I had assumed that since the "Alive Test" was configurable on the "Targets", it would only scan the hosts that were alive. So yes not a problem with the image, but a likely that of the scanner.

Thanks.
