### ISSUE TITLE
[Enhancement] Docker secret for password

### ISSUE THREAD

**Issue by sieuwe** [Secure-Compliance-Solutions-LLC/GVM-Docker#214]
I have set up GVM via a compose file.
When I use the password in plain text as an environment variable, the password is used to log in.
When I use a docker secret 
- PASSWORD=/run/secrets/gvm_password
the password is set to '/run/secrets/gvm_password' instead of the contents of the docker secret gvm_password.

**Comment by Dexus** [comment]
You are using a docker SWARM Cluster?
If not your password need to be a password not a file ;)

If you need this, we can take care to implement it. But currently this is not supportet and not a bug more a enhancement.

**Comment by sieuwe** [comment]
Yes, I'm using a swarm cluster.

**Comment by sieuwe** [comment]
The secret is shown correctly in the container. If that information helps.

**Comment by Dexus** [comment]
This Image is not ready to use the secrets right now. But will change it in a upcomming PR.
