### ISSUE TITLE
[Bug] Docker Hub image not building

### ISSUE THREAD

**Issue by pixelsquared** [Secure-Compliance-Solutions-LLC/GVM-Docker#226]
**Describe the bug**
The Docker Hub's build system does not support git submodules.

**Expected behavior**
The image is build automatically and available on docker hub.

**Additional context**
I suggest using Github actions to build the image.

**Comment by Dexus** [comment]
@pixelsquared @austinsonger it looks like the environments are not set to auth against hub.docker.com the release the workflow action is broken on that point.

**Comment by pixelsquared** [comment]
@Dexus I am working on fixing now.

**Comment by Dexus** [comment]
Thank you @pixelsquared

**Comment by Dexus** [comment]
We only need the username from one of the company members and a Token, what is the difficulty here?

**Comment by austinsonger** [comment]
@Dexus We added the credentials. But each account is limited to 1 token per account under the free tier so we are creating another account to resolve this.
