### ISSUE TITLE
[Bug] Github Action - Make GH Release Tag - Match Docker Image Tag

### ISSUE THREAD

**Issue by austinsonger** [Secure-Compliance-Solutions-LLC/GVM-Docker#231]
**Describe the bug**

![](https://i.imgur.com/08JQePo.png)

**Comment by Dexus** [comment]
Make a new release v21.4.2-v1 and it will release a version like this.

Von meinem iPhone gesendet

**Comment by Dexus** [comment]
Okay the latest version will not be created...

**Comment by austinsonger** [comment]
@Dexus  What do you mean? A version was pushed like 3 hours ago.

**Comment by Dexus** [comment]
The latest tag is not updated, It was 2 month ago last updated. I think we need to set this with a switch, on the metadata and make it on tag events  forced to latest.

**Comment by austinsonger** [comment]
@Dexus what are you looking at exactly.

![](https://i.imgur.com/zTBynFa.png)

**Comment by Dexus** [comment]
![image](https://user-images.githubusercontent.com/1674289/126847570-700b679f-8dc1-46fe-8232-f94388c2e347.png)

The "latest" tag

**Comment by austinsonger** [comment]
@Dexus this is what I see.

It looks like it is building duplicates. I don't like the tag with starting with `5564**`, it's confusing.

![](https://i.imgur.com/g6bvZkP.jpg)
