### ISSUE TITLE
emailing reports still not working

### ISSUE THREAD

**Issue by ciscoqid** [Secure-Compliance-Solutions-LLC/GVM-Docker#24]
I provided a PR yesterday to add sendmail to the container, but it is not enough to just install it from what I have found. It has to be started and that requires additional setup.  This method may work better:

https://www.michelebologna.net/2019/send-an-email-from-a-docker-container/

**Comment by pixelsquared** [comment]
Another idea would be to have sendmail use a SMTP relay

**Comment by labor4** [comment]
> Another idea would be to have sendmail use a SMTP relay

a relay to the host MTA?
isn't "standalone to remote mailserver" more elegant?

**Comment by immauss** [comment]
I used postfix and set a relayhost. Works great.  Just make sure you get the iptables correct too. In my install, I just forward to the host running the container, but it could forward to any relay host. Postfix will also let you forward to email services that require authentication.

**Comment by jsuelwald** [comment]
I need some help with that.

Running the container here, how and where do I have to configure which SMTP-Server OpenVAS should use?

**Comment by johnjore** [comment]
PR #57 created for basic postfix support (relay and port). Shamelessly copied from @immauss's repository. Worked fine with my relay server.

**Comment by pixelsquared** [comment]
PR #57 has been merged. If anyone still has problems please open a new issue.
