### ISSUE TITLE
unable to login after container startup

### ISSUE THREAD

**Issue by vinayus** [Secure-Compliance-Solutions-LLC/GVM-Docker#244]
i have been trying to get the container up and it starts fine. Issue i'm facing is i'm unable to login.
I use this command:  `sudo docker run --detach --publish 8080:9392 --publish 5432:5432 --publish 2222:22 --name gvm securecompliance/gvm:21.4.2-v2-data-full`

I have tried with different image tags available and they all give me same login error as below screen
![image](https://user-images.githubusercontent.com/3682719/127265594-1f41ace7-ba55-489a-9030-9642d8b83c16.png)

I tried passing password as env variable and still couldn't get past this stage.

Install/container stdout logs are here: https://snippi.com/s/5hyxk8z
gsad.log contains following lines

```
==> gsad.log <==
gsad main:WARNING:2021-07-28 04h52.58 utc:324: MHD: Error: received handshake message out of context.
gsad main:WARNING:2021-07-28 04h53.00 utc:324: MHD: Error: received handshake message out of context.
gsad main:WARNING:2021-07-28 04h53.00 utc:324: MHD: Error: received handshake message out of context.
gsad main:WARNING:2021-07-28 04h53.00 utc:324: MHD: Error: received handshake message out of context.
gsad main:WARNING:2021-07-28 04h53.07 utc:324: MHD: Error: received handshake message out of context.
gsad  gmp:WARNING:2021-07-28 04h53.10 utc:324: Authentication failure for 'admin' from 172.16.11.138. Status was 2.

```
Not sure if it matters, but gvmd_err.log keeps posting large debug logs mostly containing SQL statements.
```bash-5.1# ls -ltrh
total 520M
-rw-r--r-- 1 root root    0 Jul 26 17:51 redis_err.log
-rw-r--r-- 1 root root    0 Jul 26 17:51 postgresql.log
-rw-r--r-- 1 root root    0 Jul 26 17:56 gvmd.log
-rw-r--r-- 1 root root    0 Jul 26 17:56 gsad-https_err.log
-rw-r--r-- 1 root root    0 Jul 26 17:56 gsad-https.log
-rw-r--r-- 1 root root 2.9K Jul 28 03:40 postgresql_err.log
-rw-r--r-- 1 root root  346 Jul 28 03:42 ospd-openvas_err.log
-rw-r--r-- 1 root root 5.2K Jul 28 03:43 redis.log
-rw-r--r-- 1 root root  51M Jul 28 04:04 gvmd_err.log.10
-rw-r--r-- 1 root root  51M Jul 28 04:06 gvmd_err.log.9
-rw-r--r-- 1 root root  51M Jul 28 04:08 gvmd_err.log.8
-rw-r--r-- 1 root root  51M Jul 28 04:10 gvmd_err.log.7
-rw-r--r-- 1 root root  51M Jul 28 04:13 gvmd_err.log.6
-rw-r--r-- 1 root root 8.4K Jul 28 04:18 ospd-openvas.log
-rw-r--r-- 1 root root  51M Jul 28 04:24 gvmd_err.log.5
-rw-r--r-- 1 root root  51M Jul 28 04:26 gvmd_err.log.4
-rw-r--r-- 1 root root  51M Jul 28 04:27 gvmd_err.log.3
-rw-r--r-- 1 root root  51M Jul 28 04:29 gvmd_err.log.2
-rw-r--r-- 1 root root  51M Jul 28 04:31 gvmd_err.log.1
-rw-r--r-- 1 root root  20M Jul 28 04:55 gvmd_err.log
```

Please suggest if i'm missing anything here.

**Comment by Dexus** [comment]
Please try `adminpassword` as initial password for admin. And read the docs, how you can change the password if the default password not work.

**Comment by vinayus** [comment]
My bad, I assumed passing an environment variable would set the default password up as well.

thank you very much

**Comment by Dexus** [comment]
Not on the "pre-initialized" `-data` tags
