### ISSUE TITLE
[Bug] Unable to log into container.

### ISSUE THREAD

**Issue by tacticalcron** [Secure-Compliance-Solutions-LLC/GVM-Docker#245]
**Describe the bug**
When executing the container launch via directions:
`docker run --detach --publish 8080:9392 --publish 5432:5432 --publish 2222:22 --env DB_PASSWORD="postgres DB password" --env PASSWORD="<password>" --volume gvm-data:/data --name gvm securecompliance/gvm`

..the container rejects login attempts. When I remove the --env PASSWORD and try just default credentials, this also fails. 

**To Reproduce**
As explained above. 

**Expected behavior**
Login allowed

**Screenshots**
![image](https://user-images.githubusercontent.com/88111633/127385622-e8401bfb-85a2-442b-9425-e966dc654b8a.png)

**Host Device:**
 - OS: Ubuntu 20.04
 - Version: GVM version 21.4

**Image in use:**
Latest

**Additional context**
Any assistance would be helpful. It was working fine until this latest pull.

**Comment by Dexus** [comment]
https://securecompliance.gitbook.io/projects/openvas-greenbone-deployment-full-guide/faq#question-1-how-to-change-default-admin-password

Currently the `latest` tag is overwritten with the `-data-full` tag so you need to setup your password via https://securecompliance.gitbook.io/projects/openvas-greenbone-deployment-full-guide/faq#question-1-how-to-change-default-admin-password

Also please read the docs, so you know how your config should look like.
If you use the `-data-full` release default without any volumes and environment use the default password: `adminpassword` but if you use the volumes and environments, you are get the result you expect. But then you can also use for a smaller download the `-full` tag of the current release. 

Currently we have no `latest` (minimal version), `latest-full` (with optional texlive for PDF creation), `latest-data` (pre initialisated release that works without any volumes, but need to change the default password) same as `latest-data-full` tag that also includes the texlive installation.

**Comment by tacticalcron** [comment]
Got it, thanks!
