### ISSUE TITLE
[Bug] I updated image, but containter started without data

### ISSUE THREAD

**Issue by radiusmk** [Secure-Compliance-Solutions-LLC/GVM-Docker#248]
**Describe the bug**

**Reproduce**
1. Update image with "docker pull securecompliance/gvm" command
2. Remove the old container - "docker container prune"
3. Start Container - "docker run -d --restart=always --publish 443: 9392 --publish 9390: 9390 --publish 2222: 22 --publish 127.0.0.1:5432:5432 --env password = "xxxxxxxxx" --env sshd = "true" -Volume gvm-data:/data --Name gvm securecommpliance/gvm"

After that, I couldn't log in to the GVM Web Interface with the defined password, but with the "adminpassword" login was possible, but no old data.
I tried to download securecompliance/gvm:21.4.2-v2-full and start a new container, with this tag I could log in with defined password, but unfortunately the old data has not been loaded.

**Expected behavior**
Update image and start new containers with old data.
```
Can I start a container with new image whitout lost old data?

**Comment by radiusmk** [comment]
I tried update from 21.4.0-v5.

**Comment by Dexus** [comment]
Hi, 

first `-data` and `-data-full` are preinitialisated. So the default password is set.

There is no way current to move the data from old versions. But maybe if you can wait, I can create a mitigation script.

If you want to use all volumes and start fresh from scratch you Schwule use the tag 21.4.2 without any suffix.

**Comment by radiusmk** [comment]
Ok, thanks fo reply! At this moment I will continue using the old version.

**Comment by Dexus** [comment]
@radiusmk I close this issue and work on the miration in #250 
Hope I will get it done this week.
