### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by feneco91** [Secure-Compliance-Solutions-LLC/GVM-Docker#25]
Hi, any idea how to setup ldap authentication? I've just setup GVM and would like to integrate the UI authentication with our AD.

Now, when i try to configure it, the LDAP configuration page shows me "Support for LDAP is not available."

Thanks!

**Comment by ciscoqid** [comment]
I think this may require libldap2-dev to be installed prior to the build phase.

**Comment by feneco91** [comment]
Thanks @ciscoqid 

Added libldap2-dev to install-pkgs.sh and LDAP configuration is now available.
