### ISSUE TITLE
[FAQ Question 2] How can I configure them to use both?

### ISSUE THREAD

**Issue by lmj731** [Secure-Compliance-Solutions-LLC/GVM-Docker#264]
`Replace
su -c "gvmd --listen=0.0.0.0 --port=9390" 
gvm in the start.sh with
su -c "gvmd --unix-socket=/usr/var/run/gvmd.sock/gvmd.sock" gvm. 
This will create a socket in the /usr/var/run/ folder`

This is Question 2's answer. 
I wanted to use both, but there was an error. 
supervisord.conf
`command=/usr/bin/gvmd -f --listen=0.0.0.0 --port=9390 --unix-socket=/opt/socket/gvmd.sock --gnutls-priorities=SECURE128:-AES-128-CBC:-CAMELLIA-128-CBC:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1`

But there was an error. 

`supervisorctl start gvmd
gvmd: ERROR (spawn error)`

Please help me, thanks.

**Comment by Dexus** [comment]
what is the output of `/var/log/gvm/gmvd.log`,`/var/log/supervisor/gmvd.log` and `/var/log/supervisor/gmvd_err.log` ?

**Comment by lmj731** [comment]
`/var/log/supervisor/gmvd_err.log`
gvmd: --listen or --listen2 given with --unix-socket
`/var/log/gvm/gmvd.log`
md   main:MESSAGE:2021-08-19 08h22.19 utc:3481:    Greenbone Vulnerability Manager version 21.4.3 (DB revision 242)
libgvm util:MESSAGE:2021-08-19 08h22.19 utc:3481: Setting GnuPG dir to '/var/lib/gvm/gvmd/gnupg'
libgvm util:MESSAGE:2021-08-19 08h22.19 utc:3481: Using OpenPGP engine version '2.2.27'
`/var/log/supervisor/gmvd.log`
none

**Comment by Dexus** [comment]
This is not supported. If you need this you have to create a Issue at https://github.com/greenbone/gvmd
