### ISSUE TITLE
Failed to find config 'd21f6c81-2b88-4ac1-b7b4-a2a9f2ad4663'[Bug]

### ISSUE THREAD

**Issue by epochfairy** [Secure-Compliance-Solutions-LLC/GVM-Docker#279]
docker run --detach --publish 9392:9392  --volume gvm-data:/data --name gvm securecompliance/gvm:latest-data-full
# new scan config
Failed to find config 'd21f6c81-2b88-4ac1-b7b4-a2a9f2ad4663'

**Comment by Dexus** [comment]
This is not a bug. You run with old parameters. Also you need to wait for the init has finished. Look to the GSA WebUI for the Feeds.

**Comment by epochfairy** [comment]
Which command to use to execute it

**Comment by Dexus** [comment]
Maybe you will have a look to https://securecompliance.gitbook.io/projects/openvas-greenbone-deployment-full-guide

**Comment by epochfairy** [comment]
# docker run --detach --publish 8080:9392 --publish 5432:5432 --publish 2222:22 --env DB_PASSWORD="postgres DB password" --env PASSWORD="webUI password" --volume ./storage/postgres-db:/opt/database --volume ./storage/openvas-plugins:/var/lib/openvas/plugins --volume ./storage/gvm:/var/lib/gvm --volume ./storage/ssh:/etc/ssh --name gvm securecompliance/gvm:latest-data-full

docker: Error response from daemon: create ./storage/gvm: "./storage/gvm" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
