### ISSUE TITLE
Error: Could not connect to Scanner

### ISSUE THREAD

**Issue by meetgyn** [Secure-Compliance-Solutions-LLC/GVM-Docker#28]
**Help Please: every task that I send perform the same error**

Error Message ▲ | Host | Hostname | NVT | Port

Could not connect to Scanner
md manage:WARNING:2020-05-28 18h32.24 utc:9927: **manage_update_nvt_cache_osp: failed to connect to /tmp/ospd.sock**

md manage:WARNING:2020-05-28 18h32.30 UTC:9868: OSP start_scan 4f9e405a-9ae2-4797-9358-7af05b1f625d: **Could not connect to Scanner**

**Comment by pixelsquared** [comment]
Could you post the full log? Use something like pastebin.com so to not clutter up this thread.

**Comment by austinsonger** [comment]
Closing ticket until user responds.
