### ISSUE TITLE
[Bug] No Scan Configs available

### ISSUE THREAD

**Issue by nestoru** [Secure-Compliance-Solutions-LLC/GVM-Docker#280]
Steps to replicate:
1. Run the container:
```
docker run --detach --publish 8080:9392 --env PASSWORD="admin" --volume gvm-data:/data/gvm-data --name gvm securecompliance/gvm:latest-data-full
```
2. Wait till the below shows up from 'docker logs gvm --follow': 
```
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+     Greenbone Vulnerability Manager 21.4.3
Manager DB revision 242
Copyright (C) 2009-2021 Greenbone Networks GmbH
License: AGPL-3.0-or-later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
+ Your GVM container is now ready to use!                 +
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```
3. Login to https://localhost:8080 (even though PASSWORD=admin the var has no effect because the password is adminpassword)
4. Go to https://localhost:8080/scanconfigs
5. Expected: To see scan configs available. Actual: No scan configs at all. 
6. Create a target
7. Try creating a task for the target selecting the openVAS scanner
8. Expected: to save the task. Actual: Cant save with error "Failed to find config 'daba56c8-73ec-11df-a475-002264764cea'" due to #5 above.
9. Try creating a task for the target selecting the CVE scanner
10. Expected: Same failure as #8. Actual: success
11. Run the CVE scanner configured task
12. Expected: To take sometime and at least produce a report stating a false positive or any success related wording. Actual: Finishes immediately and a download of the report in CSV is empty, in PDF corrupted, in XML a valid doc but without scanning result info as shown below:
```
<report extension="xml" id="27f3eef6-2f1e-4e12-805a-0b0940eac1d0" format_id="5057e5cc-b825-11e4-9d0e-28d24461215b" content_type="text/xml"><owner><name>admin</name></owner><name>2021-09-17T09:52:24Z</name><comment></comment><creation_time>2021-09-17T09:52:24Z</creation_time><modification_time>2021-09-17T09:52:24Z</modification_time><writable>0</writable><in_use>0</in_use><task id="0cebcc18-fd2b-47f8-b4c5-4e76cddc8f00"></task><report_format id="5057e5cc-b825-11e4-9d0e-28d24461215b"><name>Anonymous XML</name></report_format></report>%  
```

**Comment by Dexus** [comment]
Please use the BUG Report Template, and read the docs: https://securecompliance.gitbook.io/projects/openvas-greenbone-deployment-full-guide
