### ISSUE TITLE
[Bug] Alpine Linux makensis is missing - Windows creds are not forming properly

### ISSUE THREAD

**Issue by elijah-tach** [Secure-Compliance-Solutions-LLC/GVM-Docker#284]
Hi, I've found an issue that creds that I'm trying to form in order to export(Windows ones) are empty. Earlier I've just added makensis to the container to fix this. But now it is based on Alpine Linux, I can't find the makensis/nsis package into the apk. And there is no Alpine compatible package on the internet. Could you help me with this/add the makensis to the image?

**Comment by Dexus** [comment]
We can't support this for alpine. But I think our default image will in the future a debian image, so you can install it there.
