### ISSUE TITLE
 Missing gvmd-log Logfile and GVM_DATA

### ISSUE THREAD

**Issue by devMarc5598** [Secure-Compliance-Solutions-LLC/GVM-Docker#287]
Dear all,

My Greenbone is running but i have no gvmd-log file in /var/log/gvm/ and the one in /var/log/supervisor/ is empty...
And as already mentioned in Missing GVM_DATA in GSA #273 (#273) the GVM_DATA is also missing...
I got this data in /var/lib/gvm/data-objects/gvmd but not in the GSA.
I think that greenbone-feed-sync --type GVMD_DATA does nothing on my deployment because I have to get the data with rsync -avrP rsync://feed.community.greenbone.net:/data-objects/gvmd/ .

Any ideas?
I think gvmd doesnt load the data in the postgresdb. So GSA has no data to show.

**GVM Versions:**
gsad: 21.4.2
gvmd: 21.4.3
openvas-scanner: 21.4.2
gvm-libs: 21.4.2
image: 21.4.3-v1

**Comment by Dexus** [comment]
If you not have the log files, please provide the details the Bugreport needs. Also I would ask you did the container ever start correctly? What do say the `docker log <containername>`?
