### ISSUE TITLE
[FAQ] How to integrate with CI?

### ISSUE THREAD

**Issue by tranphuquy19** [Secure-Compliance-Solutions-LLC/GVM-Docker#289]
I wanna configure a Gitlab CI pipeline that can run a scheduled job that can launch an OpenVAS container and perform a scan of a subnet or set of subnets that I define.

How can I do that, Is there a guide for that?

Please help me, thanks a lot!

**Comment by Dexus** [comment]
That’s right! You need to use the credentials and run the command in the container. 

How I would do it:
1. create the xml in an host temp dir.
2. start the container with the volume where the xml files are in.
3. wait for the feeds synced. (Xml)
4. create the target (xml) and run the CLI in the container
5. create the task (xml) and run the CLI in the container
6. create the start task (xml) and run the CLI in the container
7. check until the task has status 100(%) (xml) and run the CLI in the container
8. get the report (xml) and run the CLI in the container
9. stop the Container

Von meinem iPhone gesendet
