### ISSUE TITLE
Problem login in Web front end

### ISSUE THREAD

**Issue by 0xLenny** [Secure-Compliance-Solutions-LLC/GVM-Docker#29]
Hello,
i downloaded the docker image on 31 May and 
i think i installed docker image correctly with command:
docker run --detach --publish 8080:9392 -e PASSWORD="My-Random-Password-Lenny" --volume gvm-data:/data --name gvm securecompliance/gvm

Log says okay, i think...
`2020-05-31 10:47:16.698 UTC [25] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-05-31 10:47:16.698 UTC [25] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2020-05-31 10:47:16.698 UTC [25] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2020-05-31 10:47:16.704 UTC [25] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-05-31 10:47:16.750 UTC [26] LOG:  database system was interrupted while in recovery at 2020-05-31 10:34:21 UTC
2020-05-31 10:47:16.750 UTC [26] HINT:  This probably means that some data is corrupted and you will have to use the last backup for recovery.
2020-05-31 10:47:16.953 UTC [26] LOG:  database system was not properly shut down; automatic recovery in progress
2020-05-31 10:47:16.957 UTC [26] LOG:  redo starts at 0/32053EF0
2020-05-31 10:47:19.012 UTC [26] FATAL:  could not extend file "base/16385/17842": wrote only 4096 of 8192 bytes at block 337
2020-05-31 10:47:19.012 UTC [26] HINT:  Check free disk space.
2020-05-31 10:47:19.012 UTC [26] CONTEXT:  WAL redo at 0/37727580 for Heap/INSERT+INIT: off 1
2020-05-31 10:47:19.016 UTC [25] LOG:  startup process (PID 26) exited with exit code 1
2020-05-31 10:47:19.016 UTC [25] LOG:  aborting startup due to startup process failure
2020-05-31 10:47:19.024 UTC [25] LOG:  database system is shut down
pg_ctl: could not start server
Examine the log output.
9:C 31 May 10:52:32.074 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
9:C 31 May 10:52:32.074 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=9, just started
9:C 31 May 10:52:32.074 # Configuration loaded
Wait for redis socket to be created...
Testing redis status...
Redis ready.
Fixing Database folder...
Starting PostgreSQL...
Updating NVTs...
Updating CERT data...
Updating SCAP data...
Starting Open Scanner Protocol daemon for OpenVAS...
Starting Greenbone Vulnerability Manager...
admin
Starting Greenbone Security Assistant...
++++++++++++++++++++++++++++++++++++++++++++++
+ Your GVM 11 container is now ready to use! +
++++++++++++++++++++++++++++++++++++++++++++++
`

But the problem is, that i cant login with admin:admin on page http://IP-ADR:8080
This might be the problem, i used default Username admin and password admin:

`==> /usr/local/var/log/gvm/gsad.log <==
gsad  gmp:WARNING:2020-05-31 11h05.36 utc:201: Authentication failure for 'admin' from 192.168.150.21. Status was 2.

==> /usr/local/var/log/gvm/gvmd.log <==
md    gmp:WARNING:2020-05-31 11h05.36 utc:687: Authentication failure for 'admin' from unix_socket
`

EDIT: Also Chromium and Firefax in latest Kali do not work.

EDIT: I reseave :" GMP error during authentication"
Log:
`==> /usr/local/var/log/gvm/gsad.log <==
gsad  gmp:WARNING:2020-05-31 11h54.06 utc:245: Authentication failure for 'admin' from 192.168.150.21. Status was -1.

==> /usr/local/var/log/gvm/gvmd.log <==
md manage:WARNING:2020-05-31 11h54.06 utc:1068: sql_open: PQconnectStart to 'gvmd' failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
md manage:WARNING:2020-05-31 11h54.06 utc:1068: init_manage_process: sql_open failed
md manage:WARNING:2020-05-31 11h54.16 utc:161: sql_exec_internal: PQexec failed:  (7)
md manage:WARNING:2020-05-31 11h54.16 utc:161: sql_exec_internal: SQL: BEGIN;
md manage:WARNING:2020-05-31 11h54.16 utc:161: sqlv: sql_exec_internal failed
md manage:WARNING:2020-05-31 11h54.16 utc:161: manage_schedule: manage_update_nvti_cache error (Perhaps the db went down?)
md manage:WARNING:2020-05-31 11h54.16 utc:1071: sql_open: PQconnectStart to 'gvmd' failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
md manage:WARNING:2020-05-31 11h54.16 utc:1071: init_manage_process: sql_open failed
md manage:WARNING:2020-05-31 11h54.16 utc:1072: sql_open: PQconnectStart to 'gvmd' failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
md manage:WARNING:2020-05-31 11h54.16 utc:1072: init_manage_process: sql_open failed
md manage:WARNING:2020-05-31 11h54.16 utc:1073: sql_open: PQconnectStart to 'gvmd' failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
md manage:WARNING:2020-05-31 11h54.16 utc:1073: init_manage_process: sql_open failed
md manage:WARNING:2020-05-31 11h54.26 utc:161: sql_exec_internal: PQexec failed:  (7)
md manage:WARNING:2020-05-31 11h54.26 utc:161: sql_exec_internal: SQL: BEGIN;
md manage:WARNING:2020-05-31 11h54.26 utc:161: sqlv: sql_exec_internal failed
md manage:WARNING:2020-05-31 11h54.26 utc:161: manage_schedule: manage_update_nvti_cache error (Perhaps the db went down?)
md manage:WARNING:2020-05-31 11h54.26 utc:1076: sql_open: PQconnectStart to 'gvmd' failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
md manage:WARNING:2020-05-31 11h54.26 utc:1076: init_manage_process: sql_open failed
md manage:WARNING:2020-05-31 11h54.26 utc:1075: sql_open: PQconnectStart to 'gvmd' failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
md manage:WARNING:2020-05-31 11h54.26 utc:1075: init_manage_process: sql_open failed
md manage:WARNING:2020-05-31 11h54.26 utc:1077: sql_open: PQconnectStart to 'gvmd' failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
md manage:WARNING:2020-05-31 11h54.26 utc:1077: init_manage_process: sql_open failed
md manage:WARNING:2020-05-31 11h54.36 utc:161: sql_exec_internal: PQexec failed:  (7)
md manage:WARNING:2020-05-31 11h54.36 utc:161: sql_exec_internal: SQL: BEGIN;
md manage:WARNING:2020-05-31 11h54.36 utc:161: sqlv: sql_exec_internal failed
md manage:WARNING:2020-05-31 11h54.36 utc:161: manage_schedule: manage_update_nvti_cache error (Perhaps the db went down?)
md manage:WARNING:2020-05-31 11h54.36 utc:1079: sql_open: PQconnectStart to 'gvmd' failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
md manage:WARNING:2020-05-31 11h54.36 utc:1079: init_manage_process: sql_open failed
md manage:WARNING:2020-05-31 11h54.36 utc:1080: sql_open: PQconnectStart to 'gvmd' failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
md manage:WARNING:2020-05-31 11h54.36 utc:1080: init_manage_process: sql_open failed
md manage:WARNING:2020-05-31 11h54.36 utc:1081: sql_open: PQconnectStart to 'gvmd' failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
md manage:WARNING:2020-05-31 11h54.36 utc:1081: init_manage_process: sql_open failed
md manage:WARNING:2020-05-31 11h54.46 utc:161: sql_exec_internal: PQexec failed:  (7)
md manage:WARNING:2020-05-31 11h54.46 utc:161: sql_exec_internal: SQL: BEGIN;
md manage:WARNING:2020-05-31 11h54.46 utc:161: sqlv: sql_exec_internal failed
md manage:WARNING:2020-05-31 11h54.46 utc:161: manage_schedule: manage_update_nvti_cache error (Perhaps the db went down?)
md manage:WARNING:2020-05-31 11h54.46 utc:1083: sql_open: PQconnectStart to 'gvmd' failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
md manage:WARNING:2020-05-31 11h54.46 utc:1083: init_manage_process: sql_open failed
md manage:WARNING:2020-05-31 11h54.46 utc:1084: sql_open: PQconnectStart to 'gvmd' failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
md manage:WARNING:2020-05-31 11h54.46 utc:1084: init_manage_process: sql_open failed
md manage:WARNING:2020-05-31 11h54.46 utc:1085: sql_open: PQconnectStart to 'gvmd' failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
md manage:WARNING:2020-05-31 11h54.46 utc:1085: init_manage_process: sql_open failed
root@0xLenny:~# 
`

**Comment by pixelsquared** [comment]
Can you verify that there is free space available on your system?

**Comment by syafsss** [comment]
Hi @0xLenny, 

I noticed in your docker command the password is `PASSWORD="My-Random-Password-Lenny"`. Try to login with `username: admin`, `password: "My-Random-Password-Lenny"` value instead, hope this helps.
