### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by rvisc** [Secure-Compliance-Solutions-LLC/GVM-Docker#292]
**Describe the bug**
I am trying to use gvm-cli via socket, but in the image I am using (21.4.3-v1-data-full) there is no gvmd.sock. 
I tried to create gvmd.sock in /data/gvmd/ using the following Python script 
`python3 -c "import socket as s; sock = s.socket(s.AF_UNIX); sock.bind('/data/gvmd/gvmd.sock')"`
but if I run any gvm-cli command 
e.g., 
`gvm-cli socket ---socketpath /data/gvmd/gvmd.sock -xml "<get_tasks/>" `
the system always returns 
`ERROR:gvmtools.cli:Could not connect to socket /data/gvmd/gvmd.sock`
I also tried the latest docker images with same result.

**To Reproduce**
1. download  latest docker image;
2. run it;
3. open console;
4. install python and gvm-tools
5. run as gvm user the following command:
`gvm-cli socket ---socketpath /data/gvmd/gvmd.sock -xml "<get_tasks/>" `

**Expected behavior**
The xml response from gvm-cli.

**Comment by Dexus** [comment]
Only as a sidenode, if you build the image yourself, you should edit the https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/blob/master/config/supervisord.conf file.
