### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by markdesilva** [Secure-Compliance-Solutions-LLC/GVM-Docker#294]
**Describe the bug**
Last few days feeds are timing out and I get these messages in the logs:

```
Updating NVTs...
[Receiver] io timeout after 10 seconds -- exiting
....
Updating SCAP data...
....
receiving incremental file list
[Receiver] io timeout after 10 seconds -- exiting
rsync error: timeout in data send/receive (code 30) at io.c(197) [Receiver=3.2.3]
....
Updating CERT data...
....
receiving incremental file list
[Receiver] io timeout after 10 seconds -- exiting
rsync error: timeout in data send/receive (code 30) at io.c(197) [Receiver=3.2.3]
```

**To Reproduce**
1. Start the container
2. docker logs -f gvm
3. See error

**Expected behavior**
Feeds updates should download

**Screenshots**

**Host Device:**
 - OS: Ubuntu
 - Version: 20.04

**Image in use:**
Docker image from securecompliance

**Additional context**

**Comment by Dexus** [comment]
1. This is not a BUG. 
   -  It looks your firewall or the download host is blocking your requests.
2. You missed title and requested details.

**Comment by markdesilva** [comment]
Sorry about the title.

1) Updates are only run from this one IP.
2) No firewall block on anything. This was working perfectly up till yesterday and nothing has been changed on the host or container at all.

I can't seem to reach feed.community.greenbone.net from any machine (no firewall active) on any network, has the feed url changed?

**Comment by markdesilva** [comment]
Sorry about the title, I have edited it.

>     * It looks your firewall or the download host is blocking your requests.

No firewall in place.

>     * You should make sure to not run this update for different containers at the same time with the same IP. Or you get blocked, please read the Feeds Policy from greenbone.

For GVM, this container has its own IP and its the only container doing the update.

I can't reach feed.community.greenbone.net from anywhere. Has the feed url changed?

**Comment by pixelsquared** [comment]
Looks like an issue on greenbone's side.
https://community.greenbone.net/t/unable-to-connect-rsync-feed-community-greenbone-net-at-io-c/10548

**Comment by markdesilva** [comment]
Thanks @pixelsquared! I thought it was just me, nearly deleted the whole container and wanted to try from scratch.

> Looks like an issue on greenbone's side. https://community.greenbone.net/t/unable-to-connect-rsync-feed-community-greenbone-net-at-io-c/10548

**Comment by markdesilva** [comment]
Greenbone says that SYN-Cookies need to be activated.

https://community.greenbone.net/t/important-ip-and-bandwith-limitations-on-community-feed/10595/22

Any idea how we do this with the docker image?

Thank you.

**Comment by Dexus** [comment]
> Greenbone says that SYN-Cookies need to be activated.
> 
> https://community.greenbone.net/t/important-ip-and-bandwith-limitations-on-community-feed/10595/22
> 
> Any idea how we do this with the docker image?
> 
> Thank you.

The went from SYN to random early drops. And if you need SYN you need to activate them in HOST system.

alternative:
clone once a day the RSYNC Repo, and setup you system with environment for `COMMUNITY_CERT_RSYNC_FEED`, `COMMUNITY_SCAP_RSYNC_FEED`, `COMMUNITY_GVMD_DATA_RSYNC_FEED` to your local clone.
