### ISSUE TITLE
[Bug] TLSv1.1 on gsad-https 

### ISSUE THREAD

**Issue by webexppvcp** [Secure-Compliance-Solutions-LLC/GVM-Docker#295]
**Describe the bug**
The interface (port 8443 gsad-https) is sensitive to the NVT 1.3.6.1.4.1.25623.1.0.117274:
TLS 1.1 must be deprecated

**To Reproduce**
1. Scan OpenVAS himself
2. See result

**Expected behavior**
Add _-VERS-TLS1.1_ in the _gnutls-priorities_ arg of the _command_ of _gsad-https_ in the _/etc/supervisord.conf_ (like gvmd)

**Screenshots**
![Scan Result](https://user-images.githubusercontent.com/17162346/140032292-5cc687ea-b2e9-4ffd-af1c-a5fea3598dbf.png)

**Image in use:**

```
        "Id": "sha256:ed6308f4227f0153ea0c4df5c0f648fd7064eb12c0c96331f996e4aed026e050",
        "RepoTags": [
            "securecompliance/gvm:latest"
        ],
        "RepoDigests": [
            "securecompliance/gvm@sha256:b11df7b3ec5416d6409920ea2400d7ad65a193ae3bd077a13b2dbc1dead4939a"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2021-08-08T20:29:21.015414376Z",
```

**Comment by Dexus** [comment]
This is already fixed in the `dev` branche.
