### ISSUE TITLE
End of Life of the scanner engines

### ISSUE THREAD

**Issue by antonisnyc94** [Secure-Compliance-Solutions-LLC/GVM-Docker#300]
Hello,

We receive a 10/10 CVSS alert after every scan mentioning that the scanner engine has reached its end of life! Do you know what steps need to be take to remediate this? Do we need to install different packages or just update them? And does this mean that we no longer receive up to date vulnerability updates?

<img width="686" alt="Screen Shot 2021-11-15 at 7 31 57 PM" src="https://user-images.githubusercontent.com/36517441/141874292-5e65a35f-86b6-4953-a70a-637bbf1fed1c.png">

Thanks in advance,
Tony

**Comment by Dexus** [comment]
😪

**Comment by markdesilva** [comment]
I've been seeing the same thing for days.

![gvmlibsold](https://user-images.githubusercontent.com/59959024/141974015-ec6e4893-5795-4227-a09c-f0695f81b028.jpg)

Running the latest tag.

**Comment by markdesilva** [comment]
And how do we migrate the old databases to the new image? The one from the old bind gvm-data:/data to the new bind ./storage?

**Comment by anysure** [comment]
Seems to be linkable to #299

**Comment by tonnyhideyori** [comment]
I have received the same error when i check at the logs this was one of the logs
`md   main:MESSAGE:2021-11-16 12h01.56 utc:126:    Greenbone Vulnerability Manager version 21.4.3 (DB revision 242)`

**Comment by markdesilva** [comment]
> Seems to be linkable to #299

Yes, that's my post. I didn't see anyone else comment so I though I was the only one with the issues and something was wrong with my setup. At least I'm not on my own on this.

Latest version of of GVM is 21.4.4. I found other docker containers for this but oddly, even those are showing gvm-libs 21.4.2 when they should be the latest. I wonder if its a problem at the greenbone source.

**Comment by markdesilva** [comment]
In any case I'd like to find out about migrating the database from the 21.4.0-v5 and earlier tag to the newer 21.4.3 tags. The postgres versions are different, one is version 12 the new one is version 13.3. Even if I pg_dumpall the old dbs, I can't import to the new one, importing gives an error and messes up the gvm database. I thought there was going to be script provided, but I can't find it.

**Comment by markdesilva** [comment]
Seems like a greenbone bug?

Other gvm container maintainers are seeing the same issue even with 21.4.3 libs

https://github.com/immauss/openvas/issues/87
https://github.com/immauss/openvas/issues/86

**Comment by cfi-gb** [comment]
Just got pointed to this info and wanted to add some notes:

The message is shown because this docker container is very likely using the version `21.4.2` for the `openvas-scanner` component of GVM which is lacking one version behind the recent `21.4.3` one (haven't found the exact place where this version is getting pulled in).

I have some more additional (background) info here:

https://community.greenbone.net/t/21-4-3-gvmlibs-and-nvt-for-end-of-life-scan-engine/10731/2

An update to the VT in question to clarify that the version of the `openvas-scanner` component is checked by this VT for recent (and still supported) GVM version will arrive in the feed tomorrow or the day after.

**Comment by markdesilva** [comment]
Is this issue resolved with new feed updates for those using the latest tags? I’m still seeing the “outdated gym libs” warning.

**Comment by rroethof** [comment]
Just ran the feed updates and still having the issue unfortunatly

**Comment by markdesilva** [comment]
> Just ran the feed updates and still having the issue unfortunatly

Thanks for the confirmation @rroethof, guess we have to wait a little longer.

**Comment by cfi-gb** [comment]
> Just ran the feed updates and still having the issue unfortunatly

For clarification:

This can be only solved if the docker container provided by this project is updated to the most recent versions of all GVM components (seems this is currently prepared in #302).

The previously mentioned change in the feed only had updated some text parts of the message to better reflect which component needs to be updated.

**Comment by markdesilva** [comment]
Hmmm #302 seems to be having issues like the build immauss is working on.

**Comment by markdesilva** [comment]
And is there a script or something for migrating the postgres from the old setup (21.1.0) to the current tag setup?

**Comment by Dexus** [comment]
> And is there a script or something for migrating the postgres from the old setup (21.1.0) to the current tag setup?

No, it's not and maybe it will never come. :(

**Comment by markdesilva** [comment]
> No, it's not and maybe it will never come. :(

:(

Thanks @Dexus, guess I'll start downloading all my past reports and prepare to key in all the overrides, targets and scans again.

**Comment by antonisnyc94** [comment]
@austinsonger @Dexus   is there any chance the updates can be pushed to dockerhub?

**Comment by austinsonger** [comment]
@antonisnyc94 yeah trying to troubleshoot that now. You can pull from the github registry in the mean time. https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/pkgs/container/gvm-docker

**Comment by Dexus** [comment]
@austinsonger v21.4.4 PR  #302 was not finished... now it need a new PR

**Comment by austinsonger** [comment]
@Dexus It was marked as "Ready for Review" that is why I merged it.

**Comment by Dexus** [comment]
But all tests where red… ;)

Von meinem iPhone gesendet

**Comment by antonisnyc94** [comment]
Thank you @Dexus  @austinsonger !! You guys rock!

**Comment by markdesilva** [comment]
I'm taking we shouldn't pull this to update then.

**Comment by markdesilva** [comment]
Saw a newer 21.4.4-v1 release. Is this ok to use?

Also are the openvas scanner images going to be updated to 21.4.4 as well?

**Comment by austinsonger** [comment]
@markdesilva we only push releases if they are ready to be pushed to master.

**Comment by antonisnyc94** [comment]
@austinsonger @Dexus  quick question. I just saw the update in dockerhub. I only saw the Debian update. Does this mean that you guys will no longer support alpine?

**Comment by Dexus** [comment]
At the moment we are discontinuing support for Alpine, but that shouldn't be forever, at least not from my side. The problem is still that there are incompatibilities between some Linux distros. And there is some work from Greenbone and the community to fix these problems so that we can use it on all kinds of Linux distros.
