### ISSUE TITLE
Strange issue when i try to build the DEV Image

### ISSUE THREAD

**Issue by Hardzen** [Secure-Compliance-Solutions-LLC/GVM-Docker#304]
Ubuntu 18.04
docker -v
Docker version 20.10.8, build 3967b7d

Build Command:
docker build -f Dockerfile.debian -t gvmd-21.4.1 .

Strange build fail after line 173 scripts/debian/main_pkgs.sh 

node_modules/klaw/CHANGELOG.md
The command '/bin/sh -c ls -lahR /opt/setup/     && /opt/setup/scripts/debian/prepare.sh     && /opt/setup/scripts/debian/main_pkgs.sh' returned a non-zero code: 2

tar -C ${SOURCE_DIR} -x**v**zf ${SOURCE_DIR}/gsa-${gsa_version}.tar.gz
tar -C ${SOURCE_DIR}/gsa-${gsa_version}/gsa -x**v**zf ${SOURCE_DIR}/gsa-node-modules-${gsa_version}.tar.gz

When i remove the "v" vebose switch its buildung corretly 

https://github.com/Hardzen/GVM-Docker-1/commit/7e04748020ed89c50ff3d36891644da165d2994c

**Comment by Dexus** [comment]
This not work because of the latest gsa has no modules released.
