### ISSUE TITLE
Report outdated / end-of-life Scan Engine / Environment (local)

### ISSUE THREAD

**Issue by meetgyn** [Secure-Compliance-Solutions-LLC/GVM-Docker#322]
When performing a task, it returns the following error on all network IPs: Report Outdated / End-of-Life Scan Engine / Environment (Location) 
![image](https://user-images.githubusercontent.com/3695608/146272374-384aa8ed-e884-4c5b-becf-5b2cd5df3c5e.png)

**Comment by markdesilva** [comment]
You need the latest. Do not pull gvm:latest

You nee to pull the debian version. See here: 

https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/issues/312#issuecomment-976212442

**Comment by meetgyn** [comment]
> You need the latest. Do not pull gvm:latest
> 
> You nee to pull the debian version. See here:

Which one do I tide download? Can the old Docker image delete it?

**Comment by markdesilva** [comment]
> Which one do I tide download? Can the old Docker image delete it?

See my reply here https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/issues/312#issuecomment-997963980

**Comment by meetgyn** [comment]
> Which one do I tide download? Can the old Docker image delete it?

OK. However, I did not understand how to perform the procedure, I am suffering here for last week

**Comment by meetgyn** [comment]
Thank you very much for your help. I still can not make it work, but an old version on my client worked.
