### ISSUE TITLE
About update Feeds

### ISSUE THREAD

**Issue by DisMeo** [Secure-Compliance-Solutions-LLC/GVM-Docker#326]
Dear:
    How to update Feeds manually?

**Comment by markdesilva** [comment]
I think in /opt/setup/scripts there is a shell script "sync-all.sh". But restarting the docker container will automatically update the feeds as the container restarts.

**Comment by LandonStewart** [comment]
> I think in /opt/setup/scripts there is a shell script "sync-all.sh". But restarting the docker container will automatically update the feeds as the container restarts.

Is there a way to *not* update every time a container starts?

**Comment by Dexus** [comment]
> > I think in /opt/setup/scripts there is a shell script "sync-all.sh". But restarting the docker container will automatically update the feeds as the container restarts.
> 
> Is there a way to _not_ update every time the container starts?

there is a automatic update included that is running every day

**Comment by v1c5anchez** [comment]
> > I think in /opt/setup/scripts there is a shell script "sync-all.sh". But restarting the docker container will automatically update the feeds as the container restarts.
> 
> Is there a way to _not_ update every time the container starts?

Maybe by commenting out the line that spawns the update process?:

https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/blob/master/scripts/start.sh#L212
