### ISSUE TITLE
[Bug] Cannot create container image for i386

### ISSUE THREAD

**Issue by iz0bbz** [Secure-Compliance-Solutions-LLC/GVM-Docker#332]
**Describe the bug**
I'm trying to build a container image for i386 architecture on debian 11 i686, but it fails on gsa steps 
Is i386 supported?

**To Reproduce**

1. git clone https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker.git
2. cd GVM-Docker
3. podman image build -f Dockerfile.debian

**Log**
.....
-- Configuring Greenbone Security Assistant
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Git (missing: GIT_EXECUTABLE)
-- Install prefix: /usr
-- Configuring gsa
-- Found Node: /usr/bin/node (found suitable version "10.24.0", minimum required is "10.0")
-- Found Yarn: /usr/bin/yarnpkg (found suitable version "1.13.0", minimum required is "1.0")
-- Building gsa version 21.4.3
-- Configuring gsad
-- Building gsad version 21.4.3
-- Looking for clang-format...
-- clang-format not found.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
-- Checking for module 'libmicrohttpd>=0.9.0'
--   Found libmicrohttpd, version 0.9.62
-- Checking for module 'libxml-2.0'
--   Found libxml-2.0, version 2.9.4
-- Checking for module 'glib-2.0>=2.42'
--   Found glib-2.0, version 2.58.3
-- Checking for module 'libgvm_base>=21.4.1'
--   Found libgvm_base, version 21.4.3
-- Checking for module 'libgvm_util>=21.4.1'
--   Found libgvm_util, version 21.4.3
-- Checking for module 'libgvm_gmp>=21.4.1'
--   Found libgvm_gmp, version 21.4.3
-- Checking for module 'gnutls>=3.2.15'
--   Found gnutls, version 3.6.7
-- Looking for libgcrypt...
-- Looking for libgcrypt... /usr/lib/i386-linux-gnu/libgcrypt.so
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- WARNING: Doxygen is required to build the HTML docs.
-- Looking for xmltoman...
-- Looking for xmltoman... XMLTOMAN_EXECUTABLE-NOTFOUND
-- Looking for xmlmantohtml... XMLMANTOHTML_EXECUTABLE-NOTFOUND
-- WARNING: xmltoman is required to generate manpage.
-- WARNING: xmlmantohtml is required for manpage in HTML docs.
-- Configuring done
-- Generating done
-- Build files have been written to: /root/build/gsa
Scanning dependencies of target gsa
[  5%] Install gsa js dependencies
Scanning dependencies of target gsad
[ 11%] Building C object gsad/src/CMakeFiles/gsad.dir/gsad.c.o
[ 16%] Building C object gsad/src/CMakeFiles/gsad.dir/gsad_base.c.o
yarn install v1.13.0
[ 22%] Building C object gsad/src/CMakeFiles/gsad.dir/gsad_cmd.c.o
[ 27%] Building C object gsad/src/CMakeFiles/gsad.dir/gsad_credentials.c.o
[ 33%] Building C object gsad/src/CMakeFiles/gsad.dir/gsad_gmp.c.o
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
**Segmentation fault**
make[2]: *** [gsa/CMakeFiles/gsa.dir/build.make:63: gsa/node-modules.stamp] Error 139
make[1]: *** [CMakeFiles/Makefile2:91: gsa/CMakeFiles/gsa.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 38%] Building C object gsad/src/CMakeFiles/gsad.dir/gsad_gmp_arguments.c.o
[ 44%] Building C object gsad/src/CMakeFiles/gsad.dir/gsad_gmp_request.c.o
[ 50%] Building C object gsad/src/CMakeFiles/gsad.dir/gsad_http.c.o
[ 55%] Building C object gsad/src/CMakeFiles/gsad.dir/gsad_http_handler.c.o
[ 61%] Building C object gsad/src/CMakeFiles/gsad.dir/gsad_i18n.c.o
[ 66%] Building C object gsad/src/CMakeFiles/gsad.dir/gsad_session.c.o
[ 72%] Building C object gsad/src/CMakeFiles/gsad.dir/gsad_user.c.o
[ 77%] Building C object gsad/src/CMakeFiles/gsad.dir/gsad_settings.c.o
[ 83%] Building C object gsad/src/CMakeFiles/gsad.dir/utils.c.o
[ 88%] Building C object gsad/src/CMakeFiles/gsad.dir/validator.c.o
[ 94%] Linking C executable gsad
[ 94%] Built target gsad
make: *** [Makefile:130: all] Error 2
**Error: error building at STEP "RUN ls -lahR /opt/setup/     && /opt/setup/scripts/debian/prepare.sh     && /opt/setup/scripts/debian/main_pkgs.sh": error while running runtime: exit status 2**

**Host Device:**
 - OS: debian linux
 - Version: 11.2
 - uname -a: `Linux myhost 5.10.0-10-686 #1 SMP Debian 5.10.84-1 (2021-12-08) i686 GNU/Linux`

**Comment by Dexus** [comment]
You know you need do some changes for this? If you do not have a repo with your changes that makes problems, we are not able to help you.

**Comment by iz0bbz** [comment]
maybe I wasn't clear, but I made no changes at all.
I just cannot build the container image basing on this git on a i386 platform.
i386, and not x86_64.

**Comment by Dexus** [comment]
if you like to build it on a i386 you have to change some things like the base image, some packages etc. but you should know we don't support this.
