### ISSUE TITLE
[Bug] GVMD_DATA "..more than x days old."

### ISSUE THREAD

**Issue by FuMagnet** [Secure-Compliance-Solutions-LLC/GVM-Docker#334]
Hello, 

I built the following **image: securecompliance/gvm:debian-master-data** with docker-compose. Works with no problems so far. All feeds are up to date, only the **GVMD_DATA** is more than 40 days old. Updating the Docker container in bash did not bring any changes. **GVMD_DATA Version:** 20220128T1556

**Comment by Dexus** [comment]
Its not a docker related bug.

**Comment by Dexus** [comment]
And its only a cosmetic "problem" because "GVMD DATA" is not updated often.

**Comment by FuMagnet** [comment]
I understand, thanks for your quick reply!
