### ISSUE TITLE
[Enhancement]where is password for page

### ISSUE THREAD

**Issue by hbbdgyb** [Secure-Compliance-Solutions-LLC/GVM-Docker#336]
i use docker pull gvm
where is password for page

**Comment by hbbdgyb** [comment]
我知道了

**Comment by Dexus** [comment]
> Pre Initialized (`-data`) images, have a web ui password: `adminpassword` and should be changed after the deployment. Also the Postgres got a default password: `none`

if you use only the default `gvm:debian-master` your password is set via ENV on the `docker run` if do don't do this, see the quote above.
