### ISSUE TITLE
Scan container

### ISSUE THREAD

**Issue by DocSnyd3r** [Secure-Compliance-Solutions-LLC/GVM-Docker#34]
Hi,

is it possible to have a separate scanner only container which I could include to external scanners?

Or is the better way to deploy multiple containers with all the roles?

Maybe the certificate management is problematic.

**Comment by pixelsquared** [comment]
Could you check out this section of the readme and so if that does what you were asking for?

https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker#setup-remote-scanner

**Comment by DocSnyd3r** [comment]
Thanks! I'm also facing issue #53 

gvm-scanner    | Starting Open Scanner Protocol daemon for OpenVAS...
gvm-scanner    | +++++++++++++++++++++++++++++++++++++++++++++++++++++++
gvm-scanner    | + Your OpenVAS Scanner container is now ready to use! +
gvm-scanner    | +++++++++++++++++++++++++++++++++++++++++++++++++++++++
gvm-scanner    |
gvm-scanner    | -------------------------------------------------------
gvm-scanner    | Scanner id: izzim0ldwe
gvm-scanner    | cat: /data/ssh/key.pub: No such file or directory
gvm-scanner    | Public key:
gvm-scanner    | Master host key (Check that it matches the public key from the master):
gvm-scanner    | -------------------------------------------------------
gvm-scanner    |
gvm-scanner    | ++++++++++++++++
gvm-scanner    | + Tailing logs +
gvm-scanner    | ++++++++++++++++
gvm-scanner    | ==> /usr/local/var/log/gvm/openvas.log <==
gvm-scanner    | lib  nvticache:MESSAGE:2020-06-30 09h32.36 utc:45: Updated NVT cache from version 0 to 202006291206
gvm-scanner    |
gvm-scanner    | ==> /usr/local/var/log/gvm/ospd-openvas.log <==
gvm-scanner    | 2020-06-30 09:32:36,455 OSPD - openvas: INFO: (ospd_openvas.daemon) Loading vts in memory.
gvm-scanner    | 2020-06-30 09:32:59,945 OSPD - openvas: INFO: (ospd_openvas.daemon) Finish loading up vts.
gvm-scanner    |
gvm-scanner    | ==> /usr/local/var/log/gvm/ssh-connection.log <==
gvm-scanner    | Warning: Identity file /data/ssh/key not accessible: No such file or directory.
gvm-scanner    | ssh: Could not resolve hostname : Name or service not known
gvm-scanner    | Connection disrupted, retrying in 10 seconds...


compose file
version: '3'

services:
  gvm-scanner:
    image: securecompliance/gvm:scanner

    volumes:
      - gvm-scanner:/data

    container_name: gvm-scanner

    restart: unless-stopped

    environment:
       - MASTER_ADDRESS= ip
       - MASTER_PORT= 2222

volumes:
  gvm-scanner:

**Comment by disarmm** [comment]
Tracking in issue #53
