### ISSUE TITLE
Is this repo still being maintained?[Enhancement]

### ISSUE THREAD

**Issue by arshiamohammdii** [Secure-Compliance-Solutions-LLC/GVM-Docker#350]
I'm using your docker image in my project and I was wondering if the gvmd is going to live up to the greenbone latest version since the latest update to the repo goes back to 2022

**Comment by Dexus** [comment]
not from my side

**Comment by korzorro** [comment]
@arshiamohammdii This project is no longer being maintained. 

Greenbone released [Greenbone Community Containers](https://greenbone.github.io/docs/latest/22.4/container/index.html). v22.4 made a large change which involved the introduction of the MQTT broker and Notus scanner. That project doesn't necessarily work the same way and it doesn't support remote scanners, but you have to be using the most recent version for new VTs to function.

We'll be updating the README to reflect this project's end of life status.
