### ISSUE TITLE
No https access to the  Web Interface

### ISSUE THREAD

**Issue by sarritzu** [Secure-Compliance-Solutions-LLC/GVM-Docker#4]
The http connection is working fine but the https connection is refused.

I followed these instructions: https://hub.docker.com/r/securecompliance/gvm

Can you please help to troubleshoot? 

The installation was successfully completed:

`CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                    NAMES
47cbc8f24bae        securecompliance/gvm   "/bin/sh -c '/start.…"   26 minutes ago      Up 26 minutes       0.0.0.0:8080->9392/tcp   gvm
`

Last logs:

`md manage:   INFO:2019-12-05 15h53.39 utc:429: Updating DFN-CERT CVSS max succeeded.
md manage:   INFO:2019-12-05 15h53.39 utc:429: Updating Max CVSS for CERT-Bund
md manage:   INFO:2019-12-05 15h53.39 utc:429: Updating CERT-Bund CVSS max succeeded.
md manage:   INFO:2019-12-05 15h53.39 utc:429: sync_cert: Updating CERT info succeeded.
md manage:   INFO:2019-12-05 15h56.03 utc:428: Updating VTs in database ... 53487 new VTs, 0 changed VTs
md manage:   INFO:2019-12-05 15h56.13 utc:428: Updating VTs in database ... done (53487 VTs).`

The ports are listening and open

Host:
`tcp6       0      0 :::8080                 :::*                    LISTEN      3831/docker-proxy`

Container:
`tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN      10/redis-server 0.0
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      -
tcp6       0      0 :::9392                 :::*                    LISTEN      -
`
Client: Succesfully tested with `telnet <IP address> 8080`

**Comment by pixelsquared** [comment]
Unfortunately, this container does not currently generate TLS certs or support HTTPS.
We were using this container locally on the machine that docker was running on and have not required HTTPS support until now.
We will work on adding HTTPS support as soon as possible.

**Comment by sarritzu** [comment]
Thank you Joshua for the quick answer. I would suggest to change the documentation accordingly:

In the "Accessing Web Interface" section 
from `https://<IP address>:8080` to `http://<IP address>:8080`

Thanks,
Tony
