### ISSUE TITLE
How to change the logs datetime?

### ISSUE THREAD

**Issue by carlotodeschini** [Secure-Compliance-Solutions-LLC/GVM-Docker#44]
How can I change the timezone for the logs?
I changed the "/etc/timezone" file and then restarted the container but the logs are always 2 hours back,
thanks

**Comment by pixelsquared** [comment]
I will add a environment variable allow users to set the timezone.

**Comment by carlotodeschini** [comment]
Thank you very much, very appreciated.
Another question, if I can: I need to send email alerts, the event (start task) is triggered but the mail is not sent. I installed in the container the postfix MTA and the mail from the command line are sent.
Which command is used by gvm to send email outside the container?
