### ISSUE TITLE
Outdated Reports

### ISSUE THREAD

**Issue by mrod23** [Secure-Compliance-Solutions-LLC/GVM-Docker#45]
I'm seeing the below in the summary of newly scanned reports:

Report outdated Scan Engine / Environment (local)

**Comment by mrod23** [comment]
Seeing this in specific result 

Installed   GVM Libraries (gvm-libs) version:          9.0.3     Latest available GVM Libraries (gvm-libs) version: 10.0.2     Reference URL(s) for the latest available version:   https://community.greenbone.net/t/gvm-11-stable-initial-release-2019-10-14/3674   /   https://community.greenbone.net/t/gvm-10-old-stable-initial-release-2019-04-05/208
--


Full line from CSV report 

3.123.130.49 |   |   | 10 | High | VendorFix | Report outdated Scan Engine / Environment   (local) | This script checks and reports an   outdated scan engine for the following environments:            - Greenbone Source Edition   (GSE)            - Greenbone Community Edition   (GCE)            used for this scan.            NOTE: While this is not, in and of   itself, a security vulnerability, a severity is reported to make you aware       of a possible decreased scan   coverage due to e.g.:            - missing functionalities            - missing bugfixes            - incompatibilities within the   feed. | Installed GVM Libraries (gvm-libs)   version:        9.0.3     Latest available GVM Libraries (gvm-libs) version: 10.0.2     Reference URL(s) for the latest available version:   https://community.greenbone.net/t/gvm-11-stable-initial-release-2019-10-14/3674   /   https://community.greenbone.net/t/gvm-10-old-stable-initial-release-2019-04-05/208 | 1.3.6.1.4.1.25623.1.0.108560 | NOCVE | 836bc1d5-d71c-4da4-ad09-a5d38ec484c2 | Dataserver-492e17731337dae6.elb.eu-central-1.amazonaws.com | 2020-06-16T13:07:46Z | f0d5188f-d0d5-4179-92f7-b1fc31a70e17 | Update to the latest available   stable release for your scan environment. Please check the       references for more information. If   you're using packages provided by your Linux distribution please contact the   maintainer       of the used distribution/repository   and request updated packages.            If you want to accept the risk of a   possible decreased scan coverage you can set a global override for this   script as       described in the linked manual. |   |   | Details:     Report outdated Scan Engine / Environment (local)     (OID: 1.3.6.1.4.1.25623.1.0.108560)     Version used: 2020-06-10T13:24:20+0000 |   |   |   | https://www.greenbone.net/en/install_use_gce/,   https://community.greenbone.net/t/gvm-9-stable-initial-release-2017-03-07/211,   https://github.com/greenbone/,   https://docs.greenbone.net/GSM-Manual/gos-4/en/vulnerabilitymanagement.html#creating-an-override
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by pixelsquared** [comment]
You using the newest version of the container?

**Comment by mrod23** [comment]
Closing this issue out.
Running the scans using python-gvm. 
I pulled the latest and updated the python-gvm version, not seeing the outdated errors anymore.
