### ISSUE TITLE
Cannot find gvmd.sock

### ISSUE THREAD

**Issue by jskyfacts** [Secure-Compliance-Solutions-LLC/GVM-Docker#46]
I am using python-gvm for automation with the docker image but while establishing connection it fails  saying "could not find /usr/local/var/run/gvmd.sock" 
The file doesn't exist in this folder, also checked other folder /var/run etc. Couldn't find it anywhere.

**Comment by pixelsquared** [comment]
This container has the GVM listen on port 9390 not on a socket

**Comment by pllvpipalwa** [comment]
But the earlier build of the container used sockets. Because it worked for me earlier.
This means I cannot use UnixSocketConnection from python-gvm or there is a way of enabling it? Or any alternative?

**Comment by pixelsquared** [comment]
Take a look at this comment: https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/issues/43#issuecomment-646423725

**Comment by eugenbesel** [comment]
> This container has the GVM listen on port 9390 not on a socket

how can I use port 9390? 
I have started gvm container 
docker run --detach --publish 8080:9392 --env PASSWORD="Your admin password here" --volume gvm-data:/data --name gvm securecompliance/gvm
and when I try to connect via openssl:
sudo openssl s_client -connect localhost:9390
then I didnt work. Do I need private or public key for it? If yes where can I find it?

thank you for your andwer.

**Comment by pixelsquared** [comment]
You will need to expose the GVM port by adding `--publish 9390:9390` to the docker run command.

**Comment by gnikoloudakis** [comment]
You have to replace `su -c "gvmd --listen=0.0.0.0 --port=9390" gvm` in the stert.sh with `su -c "gvmd --unix-socket=/data/gvmd/gvmd.sock" gvm`. this will create a socket in the /data/gvmd folder

**Comment by austinsonger** [comment]
This was added to [gitbook documentation](https://github.com/Secure-Compliance-Solutions-LLC/gitbook/blob/master/openvas-greenbone-deployment-full-guide/faq.md)
