### ISSUE TITLE
Postgres not able to start (CU-8mc6ex)

### ISSUE THREAD

**Issue by sjwk** [Secure-Compliance-Solutions-LLC/GVM-Docker#49]
**Describe the bug**
Having been running with an earlier release (11.0), I pulled the new image (tag :latest) to update my container.  It now fails to start, giving a postgresql error relating to missing config files.
> Creating network "gvm_default" with the default driver
Creating gvm ... done
Attaching to gvm
gvm    | 8:C 23 Jun 2020 15:32:38.576 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
gvm    | 8:C 23 Jun 2020 15:32:38.576 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=8, just started
gvm    | 8:C 23 Jun 2020 15:32:38.576 # Configuration loaded
gvm    | Wait for redis socket to be created...
gvm    | Testing redis status...
gvm    | Redis ready.
gvm    | Starting PostgreSQL...
gvm    | pg_ctl: another server might be running; trying to start server anyway
gvm    | waiting for server to start....postgres: could not access the server configuration file "/data/database/postgresql.conf": No such file or directory
gvm    | pg_ctl: could not start server
gvm    | Examine the log output.
gvm    |  stopped waiting

**To Reproduce**
1. Start docker container.
2. Watch it fail.

**Expected behavior**
The container to start.

**Screenshots**

**Additional context**
Container is being run from docker-compose:
> version: "3.5"
services:
  gvm:
    container_name: gvm
    image: securecompliance/gvm
    restart: always
    env_file:
      - ./gvm.env
    ports:
      - "8080:9392"
    volumes:
      - /docker/apps/gvm/storage/data:/data

Data volume is mounted via a bind mount, so I know where it is.  Looking in there, as with #41, there are no postgresql.conf, pg_ident.conf or pg_hba.conf files, but the rest of the database files from before the image upgrade are present.  Files are all owned by UID 102/GID 104 (systemd-resolve on the host computer).

**Comment by pixelsquared** [comment]
Could you try to run this command and see if it fixes it?

```
docker run --tty --rm --volume /docker/apps/gvm/storage/data:/data --name upgrade-database-temp securecompliance/gvm:upgrade-database
```

**Comment by sjwk** [comment]
That looks like it sorted it.  Sorry, did I miss a step when I upgraded the container?
