### ISSUE TITLE
OpenVAS Scanner not available

### ISSUE THREAD

**Issue by sarritzu** [Secure-Compliance-Solutions-LLC/GVM-Docker#5]
Hello,

The Openvas Scanner is not working. 
Here the logs (from /usr/local/var/log/gvm/gvmd.log):

`md manage:WARNING:2019-12-16 10h46.41 UTC:1543: Could not connect to Scanner at /tmp/ospd.sock
md manage:WARNING:2019-12-16 10h46.51 utc:1548: manage_update_nvt_cache_osp: failed to connect to /tmp/ospd.sock
md manage:WARNING:2019-12-16 10h47.02 utc:1559: manage_update_nvt_cache_osp: failed to connect to /tmp/ospd.sock
md manage:WARNING:2019-12-16 10h47.17 utc:1580: manage_update_nvt_cache_osp: failed to connect to /tmp/ospd.sock
md manage:WARNING:2019-12-16 10h47.32 utc:1593: manage_update_nvt_cache_osp: failed to connect to /tmp/ospd.sock
`

And here the error from ospd-openvas 

`root@47cbc8f24bae:/# ospd-openvas
Traceback (most recent call last):
  File "/usr/local/bin/ospd-openvas", line 11, in <module>
    load_entry_point('ospd-openvas==1.0.0', 'console_scripts', 'ospd-openvas')()
  File "/usr/local/lib/python3.6/dist-packages/ospd_openvas-1.0.0-py3.6.egg/ospd_openvas/daemon.py", line 1454, in main
  File "/usr/local/lib/python3.6/dist-packages/ospd-2.0.0-py3.6.egg/ospd/main.py", line 122, in main
  File "/usr/local/lib/python3.6/dist-packages/ospd-2.0.0-py3.6.egg/ospd/main.py", line 103, in init_logging
FileNotFoundError: [Errno 2] No such file or directory
`

Any advise?

Thanks,
Antonio.

**Comment by pixelsquared** [comment]
Could you give the full command you used to run the container?

**Comment by sarritzu** [comment]
> Could you give the full command you used to run the container?

`docker run -d -p 8080:9392 -e PASSWORD="Your admin password here" --name gvm securecompliance/gvm`

as per provided instructions...

Also the remote connection (via gvm tools) is not available. Any advice on how to activate it?

**Comment by pixelsquared** [comment]
1. Post the full output of `docker logs gvm`

1. Verify you are using the newest image from docker hub `docker pull securecompliance/gvm`

**Comment by xytnba** [comment]
Hi， Is this bug fixed ？ I have the same problem. And I run the same command "docker run -d -p 8080:9392 -e PASSWORD="Your admin password here" --name gvm securecompliance/gvm".After I restart gvm to update the nvts,It occured this error.
Thx!

**Comment by pixelsquared** [comment]
Verify you are using the newest image by running `docker pull securecompliance/gvm`.
Could you post the full output from `docker logs gvm` to a pastebin and post the link here?

**Comment by disarmm** [comment]
To everyone having this issue, are you using WSL in windows to deploy your docker container?

**Comment by aregenscheid** [comment]
@disarmm - I'm running into this problem on Ubuntu 20.04.
