### ISSUE TITLE
Error opening in browser

### ISSUE THREAD

**Issue by meetgyn** [Secure-Compliance-Solutions-LLC/GVM-Docker#50]
**Describe the bug**

**To Reproduce**
1. Go to '.docker logs gvm =  0 error'
4. See error: I followed every procedure for installation. I ran gvm docker logs, no errors were found. However, I can't open the login screen in the browser. It gives error.

**Expected behavior**
I followed every procedure for installation. I ran gvm docker logs, no errors were found. However, I can't open the login screen in the browser. It gives error.

**Comment by pixelsquared** [comment]
What is the error you get in the browser?

**Comment by meetgyn** [comment]
nothing happens. I try to access with local ip https://127.0.0.1:8080, the page is blank. I've looked at docker logs all ok, no errors. But I can't use
another error happens when I try to run the command: docker run --detach --publish 8080: 9392 --env PASSWORD = "Your admin password here" --volume gvm-data: / data --name gvm securecompliance / gvm: lastest. A message appears saying that image not found

**Comment by frakman1** [comment]
@meetgyn There is a space between `gvm:` and `latest` in your `docker run`. Try removing the space so it looks like:
`gvm:latest`. I use the version number from [here](https://hub.docker.com/r/securecompliance/gvm/tags). Similarly for your other `:` commands.
I am using `securecompliance/gvm:11.0.1-r3`

**Comment by meetgyn** [comment]
> @meetgyn There is a space between `gvm:` and `latest` in your `docker run`. Try removing the space so it looks like:
> `gvm:latest`. I use the version number from [here](https://hub.docker.com/r/securecompliance/gvm/tags). Similarly for your other `:` commands.
> I am using `securecompliance/gvm:11.0.1-r3`

**Thank you very much for your feedback, I will take the test here.**
