### ISSUE TITLE
Unable to bind the application into Nginx Reverse Proxy - 502 Bad Gateway 

### ISSUE THREAD

**Issue by viewmithun** [Secure-Compliance-Solutions-LLC/GVM-Docker#52]
**Describe the bug**

I am able to bring the application up and running on the port 8080 - https://localhost:8080
But, I am using Nginx reverse proxy docker container along with the GVM docker container. I have certificates enabled and working through nginx reverse proxy docker container. 
Port 80 & 443 is open in Nginx reverse proxy container. 

**To Reproduce**

**GVM Docker-compose.yml file:**

  gvm:
   image: securecompliance/gvm:11.0.1-r2
   restart: always
   volumes:
     - /etc/localtime:/etc/localtime:ro
     - /data/gvm-11:/data
   ports:
     - 8080:9392
   environment:
     PASSWORD: xxxxxx
     VIRTUAL_HOST: gvm.company.com

**Nginx container:**
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/ssl:/etc/ssl:ro
      - ./nginx-certs:/etc/nginx/certs
      - ./nginx-dhparam:/etc/nginx/dhparam
      - ./nginx-conf.d:/etc/nginx/conf.d
       - ./nginx-vhost.d:/etc/nginx/vhost.d:ro

First bring up the Nginx proxy container then bring up the GVM container

**Expected behavior**
Expected behavior is when I access https://gvm.company.com/ it should bring up the GVM application. 
But, I receive "502 Bad Gateway" Error

**Screenshots**
![image](https://user-images.githubusercontent.com/13327794/85691679-57d2e000-b6f2-11ea-8c8f-5043a9e9c15d.png)

**Comment by pixelsquared** [comment]
I think that the problem is that this image by default listens on port 8080 using HTTPS with a self signed cert. Try adding these environment variables to the gvm container:
```
- HTTPS: false
- VIRTUAL_PORT=8080
```

**Comment by DocSnyd3r** [comment]
this works for me (proxy in 2nd compose file)

version: '3.4'

services:
  gvm-app:
    image: securecompliance/gvm

    volumes:
      - gvm-data:/data
      - /etc/localtime:/etc/localtime:ro

    container_name: gvm

    restart: unless-stopped

    expose:
      - "9392"

    ports:
      - "2222:22"

    environment:
      - VIRTUAL_HOST=xxx.de
      - VIRTUAL_PORT=9392
      - PASSWORD=Password1234
      - SSHD=true
      - HTTPS=false
      - TZ=DE

volumes:
  gvm-data:
    name: gvm-data

networks:
  default:
    external:
      name: nginx
