### ISSUE TITLE
scanner container credentials issue

### ISSUE THREAD

**Issue by okoester** [Secure-Compliance-Solutions-LLC/GVM-Docker#53]
**Describe the bug**
Public key is not generated when creating new scanner from securecompliance/gvm:scanner
/data/ssh/key.pub is missing.

Results from docker logs:
>
> gvmscan       | +++++++++++++++++++++++++++++++++++++++++++++++++++++++
> gvmscan       | + Your OpenVAS Scanner container is now ready to use! +
> gvmscan       | +++++++++++++++++++++++++++++++++++++++++++++++++++++++
> gvmscan       |
> gvmscan       | -------------------------------------------------------
> gvmscan       | Scanner id: ---id removed ---
> gvmscan       | cat: /data/ssh/key.pub: No such file or directory
> gvmscan       | Public key:
> gvmscan       | Master host key (Check that it matches the public key from the master):
> gvmscan       | -------------------------------------------------------
>

**To Reproduce**
1. Created docker-compose.yml [docker-compose.yml.txt](https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/files/4831152/docker-compose.yml.txt)
2. docker-compose up -d
3. After finished start looking for public key in logs
4. missing key.pub file as shown above

**Expected behavior**
Find public key to copy to GVM 11 master or have command to create public key afterwards

**Screenshots**

**Additional context**

**Comment by pixelsquared** [comment]
I was able to recreate this issue and I am working on a fix.

**Comment by pixelsquared** [comment]
It seem to have to do with using hostnames instead of ip addresses for the master.
