### ISSUE TITLE
rsync: getaddrinfo temporary failure in name resolutioin

### ISSUE THREAD

**Issue by davideperson** [Secure-Compliance-Solutions-LLC/GVM-Docker#56]
i've downloaded docker image on centos8 and tried to run it but give me this kinda of error
any idea how to fix it ?
![Solar-PuTTY_hDVPDu0maS](https://user-images.githubusercontent.com/58345409/85863535-9389aa80-b7c3-11ea-89e8-06993fc95115.png)

**Comment by pixelsquared** [comment]
Can you check if any other docker containers on this system can perform DNS lookups or if it is only this one?

**Comment by davideperson** [comment]
> Can you check if any other docker containers on this system can perform DNS lookups or if it is only this one?

i don't have any docker running atm

**Comment by DocSnyd3r** [comment]
docker run busybox nslookup google.com

**Comment by davideperson** [comment]
i've fixed  the issue adding a file docker configuration

# /etc/docker/daemon.json
{
    "dns": ["192.168.1.1", "8.8.8.8"]
}

**Comment by pixelsquared** [comment]
Glad that you got it working if you have any other problems just open a new issue.
