### ISSUE TITLE
Web interface not starting on latest release

### ISSUE THREAD

**Issue by madasus** [Secure-Compliance-Solutions-LLC/GVM-Docker#62]
no data returned on the web interface port.  I had working on a previous version of the docker image but seems to be broken now.  I wiped out all my data as well just to see but still have the same issue.

I see the process running correctly

gsad --verbose --gnutls-priorities=SECURE128:-AES-128-CBC:-CAMELLIA-128-CBC:-VERS-SSL3.0:-VERS-TLS1.0 --no-redirect --mlisten=127.0.0.1 --mport=9390 --port=9392

The only error i see during the initial boot is this - not sure if it is related

md manage:   INFO:2020-07-03 14h34.59 utc:795: Updating CPEs
md manage:WARNING:2020-07-03 14h35.00 utc:805: database must be initialised from scanner
md manage:WARNING:2020-07-03 14h35.00 utc:805: sql_exec_internal: PQexec failed: ERROR:  relation "cves" does not exist
LINE 1: ... AS severity, 75 AS qod,       'cve' AS type FROM cves WHERE...
                                                             ^
 (7)
md manage:WARNING:2020-07-03 14h35.00 utc:805: sql_exec_internal: SQL: CREATE OR REPLACE VIEW vulns AS SELECT id, uuid, name, creation_time, modification_time,        cast (cvss_base AS double precision) AS severity, qod,        'nvt' AS type FROM nvts W
HERE uuid IN   (SELECT nvt FROM results     WHERE (results.severity != -3.0)) UNION SELECT id, uuid, name, creation_time, modification_time,       cvss AS severity, 75 AS qod,       'cve' AS type FROM cves WHERE uuid IN   (SELECT nvt FROM results     WHE
RE (results.severity != -3.0)) UNION SELECT id, uuid, name, creation_time, modification_time,       max_cvss AS severity, 75 AS qod,       'ovaldef' AS type FROM ovaldefs WHERE uuid IN   (SELECT nvt FROM results     WHERE (results.severity != -3.0))
md manage:WARNING:2020-07-03 14h35.00 utc:805: sqlv: sql_exec_internal failed
md   main:MESSAGE:2020-07-03 14h35.18 utc:30:    Greenbone Vulnerability Manager version 9.0.1 (DB revision 221)
md   main:   INFO:2020-07-03 14h35.18 utc:30:    Migrating database.

it appears to finish correctly

md manage:   INFO:2020-07-03 14h48.47 utc:160: Updating user OVAL definitions.
md manage:   INFO:2020-07-03 14h48.47 utc:160: Updating CVSS scores and CVE counts for CPEs
md manage:   INFO:2020-07-03 14h53.20 utc:160: Updating CVSS scores for OVAL definitions
md manage:   INFO:2020-07-03 14h53.31 utc:160: Updating placeholder CPEs
md manage:   INFO:2020-07-03 14h55.08 utc:160: update_scap: Updating SCAP info succeeded

last line i see after restarting the docker

md manage:WARNING:2020-07-06 00h09.44 utc:207: database must be initialised from scanner

Any thoughts?

**Comment by pixelsquared** [comment]
Are you using HTTPS to connect to the web ui?

**Comment by madasus** [comment]
I have tried both but previously it was just standard HTTP.  if i do a telnet from within the docker to 9392 it connects and then if I do a GET / it just terminates the session.

**Comment by pixelsquared** [comment]
The newest version of the image defaults to HTTPS you can switch to HTTP by adding `--env HTTPS=false` to the docker run command.

**Comment by madasus** [comment]
thanks - adding that resolves the issue.  Not sure why HTTPS does not work for me.  I'll try another clean docker install.

**Comment by pixelsquared** [comment]
Closing this issue, if you have any more problems please open a new issue.
