### ISSUE TITLE
Running behind nginx proxy

### ISSUE THREAD

**Issue by srekkas** [Secure-Compliance-Solutions-LLC/GVM-Docker#63]
I am running containers behind Nginx-Proxy container.  whic automagicaly proxy to 443 or 80 ports.
How to change default 9392 port to other so container.
Maiby possible to expose 443 or 80 port so Nginx Proxy container can proxy connection to container.

**Comment by pixelsquared** [comment]
If you are referring to this: https://github.com/nginx-proxy/nginx-proxy

Then you can add a environment variable on the GVM container to tell the proxy what port to use.

Try adding this to your GVM container:

```
--env VIRTUAL_PORT=9392
```

**Comment by srekkas** [comment]
Yes, i am refering to this container.

Tried 9392 and 8080 virtual ports. Dont work,
Tried 

expose:
  - 9392

Dont't work too

My docker-compose file

_version: "2.2"

services:
  gvm:
    image: securecompliance/gvm
    restart: always
    environment:
      - VIRTUAL_HOST=gvm.domain.com
      - VIRTUAL_PORT=9392
      - PASSWORD="password"
    ports:
      - 8080:9392
    volumes:
      - gvm-data:/data
    networks:
      - default
      - nginxproxy_default
    mem_limit : 8G
    cpu_count : 5

volumes:
     gvm-data:

networks:
   default:
      driver: bridge
   nginxproxy_default:
      external: true_

**Comment by vesch** [comment]
OpenVAS by default uses HTTPS. Here is what makes nginx-proxy to work for us:
```
...
environment:
  - VIRTUAL_HOST=gvm.domain.tld
  - VIRTUAL_PROTO=https
ports:
  - 9392
...
```

**Comment by srekkas** [comment]
> OpenVAS by default uses HTTPS. Here is what makes nginx-proxy to work for us:
> 
> ```
> ...
> environment:
>   - VIRTUAL_HOST=gvm.domain.tld
>   - VIRTUAL_PROTO=https
> ports:
>   - 9392
> ...
> ```

Thanks, that works :)
