### ISSUE TITLE
/start.sh: line 189: /sync-all.sh: Permission denied

### ISSUE THREAD

**Issue by lowcontrast** [Secure-Compliance-Solutions-LLC/GVM-Docker#65]
**Describe the bug**
Starting the latest gvm Image fails with

....
/start.sh: line 189: /sync-all.sh: Permission denied

--> https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/commit/cb27e68fe9436154c0a1696a5a75f135769fec27

**Comment by pixelsquared** [comment]
I forgot to mark the sync-all.sh script as executable. I have just pushed a fix, once docker hub builds it this should be fixed.

**Comment by lowcontrast** [comment]
fixed: https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/commit/a7ccf955564b86ea2d5a9db62a7201e9603a6181
