### ISSUE TITLE
Auto update NVTS

### ISSUE THREAD

**Issue by srekkas** [Secure-Compliance-Solutions-LLC/GVM-Docker#67]
**Is your feature request related to a problem? Please describe.**
No, its not a problem

**Describe the solution you'd like**
Automatic updates on Running container

**Describe alternatives you've considered**
I tought maybe restarting container every several days, but then scans interrupts this way.

**Additional context**
Its frustrating, then you start task and remeber what you forgot update NVTS.

**Comment by pixelsquared** [comment]
This is something I was already considering adding.

Just was not sure the best way to implement this.
Some ideas are:

1. Create a script in the container that can be run with docker exec and scheduled with external cron
2. Run cron inside the container to run a update script
3. Have a bash script that runs in the background with a looped sleep statement to create a simple schedule system

**Comment by pixelsquared** [comment]
In the current master branch of the container you can run:
```
docker exec -it gvm /sync-all.sh
```

This is only available in the docker image tagged `master` right now. When I release the upgraded the image this will be included.

**Comment by srekkas** [comment]
Thanks, i try it in new image.

**Comment by markdesilva** [comment]
I use a cron to restart the container, at a particular time when I know automated scans will not be run, but with manual scans, as mentioned, sometimes the restart interrupts the scans if the scan runs too long or if we absentmindedly run the scan just before the cron starts.

**Comment by markdesilva** [comment]
By the way, when I tried pulling the new image, the gvm container didn't run? I had to delete the new one and go back to using the older image (about 2 months old). To upgrade I only need to pull the master image right?

docker pull securecompliance/gvm:master

Thanks.
