### ISSUE TITLE
Upgrade to GVM 20.08

### ISSUE THREAD

**Issue by dsvsdheeraj** [Secure-Compliance-Solutions-LLC/GVM-Docker#71]
GVM 20.08 is released couple of days back and I would like to upgrade GVM 11 to GVM 20.08 is it possible?

**Comment by pixelsquared** [comment]
We are working on getting an updated image for 20.08 out soon

**Comment by dsvsdheeraj** [comment]
Any update on GVM 20.08.
Thank you in advance

**Comment by dsvsdheeraj** [comment]
I'm running into NVT update issues. unable to run update_nvt_cache or rebuild. please find the attached image.
![GVM_test](https://user-images.githubusercontent.com/39532937/91627832-ee847d00-e97f-11ea-91cf-0955e0824f89.PNG)

**Comment by dsvsdheeraj** [comment]
Beside above error the scan ran successfully, but I was not able to find report or see report on openvas GUI. attaching screenshots.
![GVM_test1](https://user-images.githubusercontent.com/39532937/91628300-ddd60600-e983-11ea-85ed-6c7ef8d220bd.PNG)
![GVM_test2](https://user-images.githubusercontent.com/39532937/91628301-ddd60600-e983-11ea-8f25-efdcf2266063.PNG)

**Comment by pixelsquared** [comment]
Just an update on the progress of updating to 20.04.

Sorry about about the delay I have been busy with other projects lately.

The main problem seems to be loading the "GVMD_DATA" feed data. If anyone wants to help feel free but I will try to keep looking for a solution.

**Comment by pixelsquared** [comment]
I found the issue the default path for OSPd had changed in the gvm so it couldn't connect and load the NVTs. I just pushed a commit to master which should fix this problem.
