### ISSUE TITLE
CERT and SCAP data not being updated

### ISSUE THREAD

**Issue by markdesilva** [Secure-Compliance-Solutions-LLC/GVM-Docker#74]
**Describe the bug**
CERT and SCAP data are not being updated when the container restarts or by manually running the scripts cert-data-sync.sh and scap-data-sync.sh. NVTs are updated without problem.

**To Reproduce**
1. restart the container

OR

1. get a shell into the gvm container

su -c "cert-data-sync.sh" openvas-sync

and

su -c "scap-data-sync.sh" openvas-sync

**Expected behavior**
Update occurs

This has has been going on for the last 2 weeks, where only NVTs update, SCAP and CERT data do not update.

Thank you.

**Comment by markdesilva** [comment]
I should mention I have 2 remote scanners connected. These don't update SCAP and CERT data from what I can see in the start.sh script. However it doesn't explain why the SCAP and CERT update scripts don't do anything when run from the main gvm container or when it restarts.

**Comment by markdesilva** [comment]
I pulled the master successfully and now the SCAP and CERT data update. Was there a change in the feed urls?

Any idea when the master will be merged to latest? And will the scanner container be similarly updated to 20.08 too?

Thank you.

**Comment by markdesilva** [comment]
This feed url in the older pulls

rsync://feed.openvas.org:/cert-data 

isn't updated.

rsync://feed.community.greenbone.net

is updated.

Have to change the feed links to rsync://feed.community.greenbone.net in 

cert-data-sync.sh
scap-data-sync.sh

if you are not using the master.

**Comment by pixelsquared** [comment]
I just created a tag for 20.08. So once docker hub builds the image it will be available as "latest" and "20.08-v1"

**Comment by markdesilva** [comment]
Thank you! :)

> I just created a tag for 20.08. So once docker hub builds the image it will be available as "latest" and "20.08-v1"
> Sorry about the delay.

**Comment by markdesilva** [comment]
Just pulled the latest (20.08) image, works great!

One question, do I need to pull the scanner too or is that a separate image going to be updated later?

Thank you.

**Comment by pixelsquared** [comment]
I am working on getting a 20.08 scanner image out soon

**Comment by markdesilva** [comment]
Awesome! Thank you!

> I am working on getting a 20.08 scanner image out soon.
> If you ever want to chat about this docker image we have a Gitter chat room.
