### ISSUE TITLE
Scanner can't be verified and all scans result in 'error'

### ISSUE THREAD

**Issue by markdesilva** [Secure-Compliance-Solutions-LLC/GVM-Docker#76]
**Describe the bug**
Scanner cannot be verified - error "Service unavailable"

**To Reproduce**
1. Run any scan
2. See error

**Expected behavior**
Scan runs and completes

**Screenshots**

**Additional context**

Sorry just ran into an issue. The scanner fails because of this error:

**Could not connect to Scanner at /tmp/ospd.sock**

I found the ospd.sock in **/var/run/ospd/ospd.sock**

I had to create a soft link from /tmp to /var/run/ospd/ospd.sock for the scanner to work.

**Comment by markdesilva** [comment]
By the way this is for the latest pull (v20.08).

**Comment by markdesilva** [comment]
After doing the softlink, the scan runs, I am emailed at the end of the scan, but where previously I have an attached PDF of the scan results, now I don't get any report attached.

I guess this has to do with the reports bug I also reported.

**Comment by pixelsquared** [comment]
The socket issue is because the old location of ospd socket is saved in the database so I need to add script to update the existing database with the new scanner socket location.

**Comment by pixelsquared** [comment]
I just pushed a commit to the master branch that add a link for the old OSPd socket location
