### ISSUE TITLE
Remote Scanner - Permission denied (publickey)

### ISSUE THREAD

**Issue by arkhelieldan** [Secure-Compliance-Solutions-LLC/GVM-Docker#78]
**Describe the bug**
I followed the step by step document for installing the Remote Scanner, but I am receiving permission denied messages on the remote scanner machine:

```
gvm @ ip: Permission denied (publickey).
Connection disrupted, retrying in 10 seconds ...
gvm @ ip: Permission denied (publickey).
Connection disrupted, retrying in 10 seconds ...
gvm @ ip: Permission denied (publickey).
Connection disrupted, retrying in 10 seconds ...
gvm @ ip: Permission denied (publickey).
Connection disrupted, retrying in 10 seconds ...
gvm @ ip: Permission denied (publickey).
Connection disrupted, retrying in 10 seconds ...
```

https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/wiki/Setup-Remote-scanner
**To Reproduce**
1. After run the docker 
`docker run --detach --volume scanner:/data --env MASTER_ADDRESS={IP or Hostname of GVM container} --env MASTER_PORT=2222 --name scanner securecompliance/gvm:scanner
`
 and download and run all tasks of docker such as NVT update i receive this message.

2. Error:
```
gvm @ ip: Permission denied (publickey).
Connection disrupted, retrying in 10 seconds ...
gvm @ ip: Permission denied (publickey).
Connection disrupted, retrying in 10 seconds ..
```.



**Expected behavior**
Run scanner to ADD to GVM Manager

I'm using in AWS and checked all Security Groups permissions. The machines can communicate.

**Comment by pixelsquared** [comment]
Just to make sure, did you run the `docker exec -it gvm /add-scanner.sh` command on the gvm master?

**Comment by arkhelieldan** [comment]
Yes, i did add-scanner.sh

**Comment by arkhelieldan** [comment]
Sorry, retracing the steps, I forgot to include the scanner ID when the deployment is finished.

It worked !

**Comment by pixelsquared** [comment]
Glad you got it working. I will close this issue now.
