### ISSUE TITLE
Response Error 400. One of PORT_LIST and PORT_RANGE are required

### ISSUE THREAD

**Issue by omok314159** [Secure-Compliance-Solutions-LLC/GVM-Docker#79]
**Describe the bug**
On latest docker image, I get "Response Error 400" when I tried to create new task by using gvm-tools(which I copied under /data).
 
**To Reproduce**
1. Copy gvm-tools under /data.
2. Run /usr/local/bin/gvm-script as below;
docker exec -u gvm -it gvm /usr/local/bin/gvm-script --gmp-username admin --gmp-password [pass] tls --port=9390 --host=localhost /data/gvm-tools/scripts/scan-new-system.gmp.py [Target] .
3. I got error as below;
Response Error 400. One of PORT_LIST and PORT_RANGE are required

**Expected behavior**
On last docker image, I could create new task.
docker exec -u gvm -it gvm /usr/local/bin/gvm-script --gmp-username admin --gmp-password [password] tls --port=9390 /data/gvm-tools/scripts/scan-new-system.gmp.py [Target]    
Started scan of host [Target]. Corresponding report ID is d53ac584-0218-4a35-a8e1-41e45f148b82

**Screenshots**
N/A
**Additional context**
I found 127.0.0.1:9390 is listen on current image;  
tcp        0      0 127.0.0.1:9390          0.0.0.0:*               LISTEN      -  

On last image, 0.0.0.0:9390 was listen as below;  
tcp        0      0 0.0.0.0:9390            0.0.0.0:*               LISTEN      -

**Comment by FiveOFive** [comment]
I ran into the same and found that it is a compatibility change in the GMP protocol for 20.8

```
In short: Default port list removed from CREATE_TARGET.

CREATE_TARGET will no longer automatically add a port list to the target if a port list or range is not given. In other words, it is now mandatory to supply either PORT_LIST or PORT_RANGE.

As a side effect wizards that use CREATE_TARGET now provide their own default if no "port_list_id" param is given: "All IANA assigned TCP", which has UUID 33d0cd82-57c6-11e1-8ed1-406186ea4fc5. 
```

See the official docs here - https://docs.greenbone.net/API/GMP/gmp-20.08.html#changes

**Comment by omok314159** [comment]
Dear, [FiveOFive](https://github.com/FiveOFive),

Many thanks for your information.
I modified scan-new-system.gmp.py for adding Port_List UUID, then It works fine!

Kind Regards,

OMO

[patch_scan_new_system.txt](https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/files/5259287/patch_scan_new_system.txt)
