### ISSUE TITLE
manage_update_nvt_cache_osp: failed to connect to /tmp/ospd.sock FIX

### ISSUE THREAD

**Issue by Krattjeh** [Secure-Compliance-Solutions-LLC/GVM-Docker#8]
I have fixed the: failed to connect to /tmp/ospd.sock with the following:

1: Delete: /var/run/ospd.pid
2: Give write persmission to: /tmp/gvm-sync-cert AND /tmp/gvm-sync-scap

Every time the Container is restarted you have to do this again.

Is there a way to fix this?

**Comment by pixelsquared** [comment]
This issue should be fixed with the latest commit

**Comment by pixelsquared** [comment]
I take back what I just said it does not seem fixed. Do you know why you need to give write persmission to: /tmp/gvm-sync-cert AND /tmp/gvm-sync-scap ?

**Comment by pixelsquared** [comment]
Ok now it seems to be fixed
