### ISSUE TITLE
GMP Refusing Connections

### ISSUE THREAD

**Issue by Khalid34ktt** [Secure-Compliance-Solutions-LLC/GVM-Docker#87]
**Describe the bug**
I've run the newer version 20 container in a testbed environment; an environment I also have the older version 11 container running. However, I can't seem to connect to the version 20 container's API. I am thrown a connection reset by peer error instead.

**To Reproduce**
1. Download version 20 container
2. Download gvm-tools
3. Attempt to connect through via gvm-tools to the management API (example: ~ gvm-pysehll -c config/configfile.conf tls)

**Expected behavior**
Generally this would open an interactive python shell. The interactive python shell opens when I alter my configuration file that gvm-tools uses, to point to the API port for the version 11 container. However, as described, when pointing to the version 20 containers API port, it fails to connect.

**Additional context**
Run on an Ubuntu machine

**Comment by pixelsquared** [comment]
I believe the problem is that the GVM bind ip address was changed by mistake.

**Comment by AshleyRoll** [comment]
I had the same problem, just assumed it was the configured like that to harden the security.

My solution was to 
* enable SSH, and have docker map it to port `9222` 
* add a public key to `/data/scanner-ssh-keys/authorized_keys`
* Then use ssh port forwarding to access the API port with `ssh -N -L 9390:localhost:9390 gvm@localhost -p 9222 -i <private key file>`

This can be configured to access the container' API port from any machine that can connect to the exposed 9222 ssh port by changing the ssh host. Once you run this, you then have a `localhost:9390` port mapped into the container tunnelled securely over ssh. You can then tell `python-gvm` or `gvm-cli` to connect with TLS to that port.

Hope that helps.
Ash.

**Comment by robjpope** [comment]
+1 same issue.
