### ISSUE TITLE
Scan /16 range

### ISSUE THREAD

**Issue by arkhelieldan** [Secure-Compliance-Solutions-LLC/GVM-Docker#91]
I'm using the latest build, but I'm having problems with scanning in the cloud, I believe it's openvas' own, but it doesn't allow scheduling a scan or creating a list of targets with range / 16.

I have a VPC 10.10.0.0/16 and I need to scan new hosts that appear, since if I update the list with new IPs I will have to delete the schedule, the results and the current target.

Is there any way to scan with this range? I read that it is possible, but only if you make any changes to the GVMD.

**Expected behavior**
Schedule / 16 range.

**Current behavior**
Informs that it is not a valid entry.

I read in this topic about increase scan of gvmd: https://community.greenbone.net/t/gmp-scanner/2050/22 and https://lists.wald.intevation.org/pipermail/openvas-discuss/2016-June/009701.html
But i dont know to use this in docker to scan /16 range.

**Comment by disarmm** [comment]
I've tried that old fix and it doesn't seem to work anymore. We will continue to look into it.

**Comment by rroethof** [comment]
Any update on this specific item as I walked into this issue myself today

**Comment by Dexus** [comment]
You need to split this to /24 subnets it’s (I hope - I read it somewhere) a known Limitation of GVM. 

Von meinem iPhone gesendet
