### ISSUE TITLE
Change Default Admin Password

### ISSUE THREAD

**Issue by jpmorris-iso** [Secure-Compliance-Solutions-LLC/GVM-Docker#93]
When I try to reset the admin password using the command below it does not work.
gvmd --user=admin --new-password=new_password

docker logs show an issue connecting to sql

md   main:MESSAGE:2020-10-07 10h21.09 utc:5489:    Greenbone Vulnerability Manager version 20.08.0 (DB revision 233)
md manage:   INFO:2020-10-07 10h21.09 utc:5489:    Modifying user password.
md manage:WARNING:2020-10-07 10h21.09 utc:5489: sql_open: PQconnectPoll failed
md manage:WARNING:2020-10-07 10h21.09 utc:5489: sql_open: PQerrorMessage (conn): FATAL:  role "root" does not exist
md manage:WARNING:2020-10-07 10h21.09 utc:5489: init_manage_process: sql_open failed
2020-10-07 10:23:08.339 UTC [5584] FATAL:  role "root" does not exist

Attempting to change on the console gives a permission denied error.

Thanks

**Comment by NimaSaed** [comment]
You need to run 

`su -c "gvmd --user=admin --new-password=new_password" gvm`

**Comment by jpmorris-iso** [comment]
Thank you so much, that worked a treat. Is that in documentation somewhere? I couldn’t find it?

Thanks again,

JP

**Comment by disarmm** [comment]
This isn't in our documentation because its covered in the greenbone official documentation.

We will review our documentation and potentially add some links to official guides for certain components.

**Comment by austinsonger** [comment]
Added to our documentation.
