### ISSUE TITLE
Could not get it to work on windows 10 docker

### ISSUE THREAD

**Issue by juan-carvajal** [Secure-Compliance-Solutions-LLC/GVM-Docker#97]
This is the docker logs, it says the container is ready to use.
![image](https://user-images.githubusercontent.com/39658930/95899023-859d6c80-0d55-11eb-892d-6e0393b6b89b.png)

Port forwarding set to 8080
![image](https://user-images.githubusercontent.com/39658930/95899059-9817a600-0d55-11eb-9bad-b8be5f35fb46.png)

No response on web browser.
![image](https://user-images.githubusercontent.com/39658930/95899102-a960b280-0d55-11eb-8241-73af85ade19e.png)

**Comment by dicksnel** [comment]
Use https
