### ISSUE TITLE
Docker RUN error

### ISSUE THREAD

**Issue by meetgyn** [Secure-Compliance-Solutions-LLC/GVM-Docker#98]
**Describe the bug**

docker run 3e3e6363ad50 

docker: Error response from daemon: pull access denied for 3e3e6363ad50, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by disarmm** [comment]
are you trying to use an image id to start it?

please reference our documentation

https://app.gitbook.com/@securecompliance/s/projects/openvas-greenbone-deployment-full-guide/deploying-greenbone-gvm-gsa-with-openvas

**Comment by meetgyn** [comment]
Now with this manual I managed to make it work Thank you very much

**Comment by disarmm** [comment]
Glad that helped. We're trying to improve our documentation.
