### ISSUE TITLE
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in name resolution

### ISSUE THREAD

**Issue by YilunHunag** [Secure-Compliance-Solutions-LLC/GVM-Docker#99]
I am running a container using the image on centos8, and it shows the message:
"
Updating NVTs...
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in name resolution
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
Updating GVMd data...
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in name resolution
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
Updating SCAP data...
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in name resolution
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
Updating CERT data...
rsync: getaddrinfo: feed.community.greenbone.net 873: Temporary failure in name resolution
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]

"
I tried a method from a closed issue that talk about this, but it's not work. 
any other method can help me to fix it?

**Comment by disarmm** [comment]
what do you get if you run

curl feed.community.greenbone.net

**Comment by YilunHunag** [comment]
> what do you get if you run
> 
> curl feed.community.greenbone.net

I got:
"curl: (52) Empty reply from server".

**Comment by disarmm** [comment]
So you can resolve the DNS and reach that IP. Try running

netcat feed.community.greenbone.net 873

**Comment by YilunHunag** [comment]
> So you can resolve the DNS and reach that IP. Try running
> 
> netcat feed.community.greenbone.net 873

I got :
```
@RSYNCD:` 31.0
Greenbone community feed server - http://feed.community.greenbone.net/
This service is hosted by Greenbone Networks - http://www.greenbone.net/

All transactions are logged.

If you have any questions, please use the Greenbone community portal.
See https://community.greenbone.net for details.

By using this service you agree to our terms and conditions.

Only one sync per time, otherwise the source ip will be temporarily blocked.
```
then I press Enter :

`@ERROR: protocol startup error`

Enter again :

`Ncat: Broken pipe.`

**Comment by disarmm** [comment]
That all looks good. How long has this been happening? Have you restarted the container?

Have you done anything unique to your docker network that could prevent it from accessing the internet? You could try connecting to the container and running the netcat command from inside the container.

**Comment by YilunHunag** [comment]
well, it just happened maybe 2 or 3 days.
I never run this container before, it's a new VM、clear OS and first test about running docker for gvm.

**Comment by jskyfacts** [comment]
I am having the same issue since  more than a week. And I have not made any changes. It has been working fine since months before this issue occurred suddenly one day.

**Comment by disarmm** [comment]
@jskyfacts your problem is easier. You just need to update the container. They transitioned from the openvas.org feed to the greenbone feed and shut down the old feed on Sept 30th. You can read about it using the link below

https://community.greenbone.net/t/community-feed-url-consolidation/5338

**Comment by jskyfacts** [comment]
@disarmm How do I update the container without loosing my previous configuration and data?

**Comment by disarmm** [comment]
@jskyfacts are you using persistent volumes for your containers? if so, you can just update and use the same volume. If not, there isn't an easy way to migrate your data.

The least difficult way would be:
Export XML report for each scan report you need to migrate (if you've run one scan 100 times, you'll need to do 100 different exports)
From the Task view, you can create a "task container" and name it the same as your old task
Once created, there will be an import button. You can then import your individual scans.

you could probably script something but we dont have anything available for that.

**Comment by jskyfacts** [comment]
I am using persistent volumes. Sorry for being so naïve but just this command will work right?
docker run --detach --publish 8080:9392 --env PASSWORD="Your admin password here" --volume gvm-data:/data --name gvm securecompliance/gvm:latest
![image](https://user-images.githubusercontent.com/55120792/97666204-281e5500-1aa3-11eb-80e5-40b8d581a59b.png)

**Comment by disarmm** [comment]
you need to pull the new container first. i'd pull the 11.0.1-v1 version for now. We've had some issues with the latest.

```docker pull securecompliance/gvm:11.0.1-v1
remove the old container
then run
''' docker run --detach --publish 8080:9392 --env PASSWORD="Your admin password here" --volume gvm-data:/data --name gvm securecompliance/gvm:11.0.1-v1
